[app]
httpAddr = ":8551"
grpcAddr = ":8661"
httpAddrNonMTLS = "8085"
storage = "mongodb"

[app.metadata]
name = "api_gateway"


[database]
mongoURI= "mongodb://admin:admin@mongodb:27017/api-gateway?authSource=admin"
collections = ["events", "repos", "users"]
name= "api-gateway"

[tls]
certPath="/etc/api-gateway/certs/tls.crt"
keyPath="/etc/api-gateway/certs/tls.key"
caPath="/etc/api-gateway/certs/ca.pem"

[coreDNS]
addr= "coredns:53"

[cfssl]
apiUrl= "https://persys-cfssl:8888"

# Prow scheduler configuration for proxying
[prow]
schedulerAddr = "prow-scheduler:8085"
enableProxy = true
discoveryDomain = "persys.local"
discoveryService = "_prow-scheduler"

[github]
webHookURL = "http://persys.eastus.cloudapp.azure.com/webhook"
webHookSecret = "SECRET"

[github.auth]
clientID = "SECRET"
clientSecret = "SECRET"

[log]
lokiEndpoint="http://loki:3301"
level = "debug"

[telemetry]
addr = "http://jaeger:14268/api/traces"