// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: control.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentControl_RegisterNode_FullMethodName               = "/persys.control.v1.AgentControl/RegisterNode"
	AgentControl_Heartbeat_FullMethodName                  = "/persys.control.v1.AgentControl/Heartbeat"
	AgentControl_ApplyWorkload_FullMethodName              = "/persys.control.v1.AgentControl/ApplyWorkload"
	AgentControl_DeleteWorkload_FullMethodName             = "/persys.control.v1.AgentControl/DeleteWorkload"
	AgentControl_RetryWorkload_FullMethodName              = "/persys.control.v1.AgentControl/RetryWorkload"
	AgentControl_DrainNode_FullMethodName                  = "/persys.control.v1.AgentControl/DrainNode"
	AgentControl_UndrainNode_FullMethodName                = "/persys.control.v1.AgentControl/UndrainNode"
	AgentControl_TaintNode_FullMethodName                  = "/persys.control.v1.AgentControl/TaintNode"
	AgentControl_UntaintNode_FullMethodName                = "/persys.control.v1.AgentControl/UntaintNode"
	AgentControl_SetNodeLabel_FullMethodName               = "/persys.control.v1.AgentControl/SetNodeLabel"
	AgentControl_DeleteNodeLabel_FullMethodName            = "/persys.control.v1.AgentControl/DeleteNodeLabel"
	AgentControl_SubmitAutomationSuggestion_FullMethodName = "/persys.control.v1.AgentControl/SubmitAutomationSuggestion"
	AgentControl_ListNodes_FullMethodName                  = "/persys.control.v1.AgentControl/ListNodes"
	AgentControl_GetNode_FullMethodName                    = "/persys.control.v1.AgentControl/GetNode"
	AgentControl_ListWorkloads_FullMethodName              = "/persys.control.v1.AgentControl/ListWorkloads"
	AgentControl_GetWorkload_FullMethodName                = "/persys.control.v1.AgentControl/GetWorkload"
	AgentControl_GetClusterSummary_FullMethodName          = "/persys.control.v1.AgentControl/GetClusterSummary"
	AgentControl_ListEvents_FullMethodName                 = "/persys.control.v1.AgentControl/ListEvents"
	AgentControl_WatchEvents_FullMethodName                = "/persys.control.v1.AgentControl/WatchEvents"
	AgentControl_ControlStream_FullMethodName              = "/persys.control.v1.AgentControl/ControlStream"
	AgentControl_CreateDisk_FullMethodName                 = "/persys.control.v1.AgentControl/CreateDisk"
	AgentControl_ListDisks_FullMethodName                  = "/persys.control.v1.AgentControl/ListDisks"
	AgentControl_GetDisk_FullMethodName                    = "/persys.control.v1.AgentControl/GetDisk"
	AgentControl_DeleteDisk_FullMethodName                 = "/persys.control.v1.AgentControl/DeleteDisk"
	AgentControl_CreateBucket_FullMethodName               = "/persys.control.v1.AgentControl/CreateBucket"
	AgentControl_ListBuckets_FullMethodName                = "/persys.control.v1.AgentControl/ListBuckets"
	AgentControl_GetBucket_FullMethodName                  = "/persys.control.v1.AgentControl/GetBucket"
	AgentControl_DeleteBucket_FullMethodName               = "/persys.control.v1.AgentControl/DeleteBucket"
	AgentControl_GetBucketAccess_FullMethodName            = "/persys.control.v1.AgentControl/GetBucketAccess"
	AgentControl_ListBucketObjects_FullMethodName          = "/persys.control.v1.AgentControl/ListBucketObjects"
)

// AgentControlClient is the client API for AgentControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentControlClient interface {
	// Registration
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	// Heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// Workload lifecycle
	ApplyWorkload(ctx context.Context, in *ApplyWorkloadRequest, opts ...grpc.CallOption) (*ApplyWorkloadResponse, error)
	DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error)
	// Retry trigger
	RetryWorkload(ctx context.Context, in *RetryWorkloadRequest, opts ...grpc.CallOption) (*RetryWorkloadResponse, error)
	// Node management
	DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error)
	UndrainNode(ctx context.Context, in *UndrainNodeRequest, opts ...grpc.CallOption) (*UndrainNodeResponse, error)
	TaintNode(ctx context.Context, in *TaintNodeRequest, opts ...grpc.CallOption) (*TaintNodeResponse, error)
	UntaintNode(ctx context.Context, in *UntaintNodeRequest, opts ...grpc.CallOption) (*UntaintNodeResponse, error)
	SetNodeLabel(ctx context.Context, in *SetNodeLabelRequest, opts ...grpc.CallOption) (*SetNodeLabelResponse, error)
	DeleteNodeLabel(ctx context.Context, in *DeleteNodeLabelRequest, opts ...grpc.CallOption) (*DeleteNodeLabelResponse, error)
	SubmitAutomationSuggestion(ctx context.Context, in *SubmitAutomationSuggestionRequest, opts ...grpc.CallOption) (*SubmitAutomationSuggestionResponse, error)
	// Cluster and node management visibility
	ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error)
	GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error)
	GetClusterSummary(ctx context.Context, in *GetClusterSummaryRequest, opts ...grpc.CallOption) (*GetClusterSummaryResponse, error)
	// Cluster-wide events: node joined, node lost, node left, workload
	// scheduled, drift detected, retries, reschedules, etc (see
	// internal/scheduler/events.go for producers). ListEvents is a
	// plain unary call (auto-bridged to REST by persys-gateway's
	// reflection-based grpcbridge, no gateway changes needed). WatchEvents
	// is a server-streaming call — grpcbridge explicitly does not bridge
	// streaming RPCs, so consumers that need HTTP (e.g. a browser
	// dashboard) go through a hand-written SSE endpoint on the gateway
	// instead of the generic bridge; a gRPC client (e.g. persysctl) can
	// call it directly.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SchedulerEventView], error)
	// Optional future streaming channel
	ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error)
	// Standalone disk inventory (managed volumes)
	CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error)
	ListDisks(ctx context.Context, in *ListDisksRequest, opts ...grpc.CallOption) (*ListDisksResponse, error)
	GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*GetDiskResponse, error)
	DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*DeleteDiskResponse, error)
	// Object storage (Ceph RGW / S3-compatible buckets)
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error)
	GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*GetBucketResponse, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error)
	GetBucketAccess(ctx context.Context, in *GetBucketAccessRequest, opts ...grpc.CallOption) (*GetBucketAccessResponse, error)
	ListBucketObjects(ctx context.Context, in *ListBucketObjectsRequest, opts ...grpc.CallOption) (*ListBucketObjectsResponse, error)
}

type agentControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentControlClient(cc grpc.ClientConnInterface) AgentControlClient {
	return &agentControlClient{cc}
}

func (c *agentControlClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentControl_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ApplyWorkload(ctx context.Context, in *ApplyWorkloadRequest, opts ...grpc.CallOption) (*ApplyWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWorkloadResponse)
	err := c.cc.Invoke(ctx, AgentControl_ApplyWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DeleteWorkload(ctx context.Context, in *DeleteWorkloadRequest, opts ...grpc.CallOption) (*DeleteWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkloadResponse)
	err := c.cc.Invoke(ctx, AgentControl_DeleteWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) RetryWorkload(ctx context.Context, in *RetryWorkloadRequest, opts ...grpc.CallOption) (*RetryWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryWorkloadResponse)
	err := c.cc.Invoke(ctx, AgentControl_RetryWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DrainNode(ctx context.Context, in *DrainNodeRequest, opts ...grpc.CallOption) (*DrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DrainNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_DrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) UndrainNode(ctx context.Context, in *UndrainNodeRequest, opts ...grpc.CallOption) (*UndrainNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UndrainNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_UndrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) TaintNode(ctx context.Context, in *TaintNodeRequest, opts ...grpc.CallOption) (*TaintNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaintNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_TaintNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) UntaintNode(ctx context.Context, in *UntaintNodeRequest, opts ...grpc.CallOption) (*UntaintNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UntaintNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_UntaintNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) SetNodeLabel(ctx context.Context, in *SetNodeLabelRequest, opts ...grpc.CallOption) (*SetNodeLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetNodeLabelResponse)
	err := c.cc.Invoke(ctx, AgentControl_SetNodeLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DeleteNodeLabel(ctx context.Context, in *DeleteNodeLabelRequest, opts ...grpc.CallOption) (*DeleteNodeLabelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeLabelResponse)
	err := c.cc.Invoke(ctx, AgentControl_DeleteNodeLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) SubmitAutomationSuggestion(ctx context.Context, in *SubmitAutomationSuggestionRequest, opts ...grpc.CallOption) (*SubmitAutomationSuggestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitAutomationSuggestionResponse)
	err := c.cc.Invoke(ctx, AgentControl_SubmitAutomationSuggestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListNodes(ctx context.Context, in *ListNodesRequest, opts ...grpc.CallOption) (*ListNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodesResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListWorkloads(ctx context.Context, in *ListWorkloadsRequest, opts ...grpc.CallOption) (*ListWorkloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkloadsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListWorkloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetWorkload(ctx context.Context, in *GetWorkloadRequest, opts ...grpc.CallOption) (*GetWorkloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkloadResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetWorkload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetClusterSummary(ctx context.Context, in *GetClusterSummaryRequest, opts ...grpc.CallOption) (*GetClusterSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterSummaryResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetClusterSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (*ListEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEventsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SchedulerEventView], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[0], AgentControl_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, SchedulerEventView]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_WatchEventsClient = grpc.ServerStreamingClient[SchedulerEventView]

func (c *agentControlClient) ControlStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ControlMessage, ControlMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentControl_ServiceDesc.Streams[1], AgentControl_ControlStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ControlMessage, ControlMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ControlStreamClient = grpc.BidiStreamingClient[ControlMessage, ControlMessage]

func (c *agentControlClient) CreateDisk(ctx context.Context, in *CreateDiskRequest, opts ...grpc.CallOption) (*CreateDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDiskResponse)
	err := c.cc.Invoke(ctx, AgentControl_CreateDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListDisks(ctx context.Context, in *ListDisksRequest, opts ...grpc.CallOption) (*ListDisksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDisksResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListDisks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetDisk(ctx context.Context, in *GetDiskRequest, opts ...grpc.CallOption) (*GetDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiskResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DeleteDisk(ctx context.Context, in *DeleteDiskRequest, opts ...grpc.CallOption) (*DeleteDiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDiskResponse)
	err := c.cc.Invoke(ctx, AgentControl_DeleteDisk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, AgentControl_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListBuckets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetBucket(ctx context.Context, in *GetBucketRequest, opts ...grpc.CallOption) (*GetBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketResponse)
	err := c.cc.Invoke(ctx, AgentControl_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) GetBucketAccess(ctx context.Context, in *GetBucketAccessRequest, opts ...grpc.CallOption) (*GetBucketAccessResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketAccessResponse)
	err := c.cc.Invoke(ctx, AgentControl_GetBucketAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentControlClient) ListBucketObjects(ctx context.Context, in *ListBucketObjectsRequest, opts ...grpc.CallOption) (*ListBucketObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketObjectsResponse)
	err := c.cc.Invoke(ctx, AgentControl_ListBucketObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentControlServer is the server API for AgentControl service.
// All implementations must embed UnimplementedAgentControlServer
// for forward compatibility.
type AgentControlServer interface {
	// Registration
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	// Heartbeat
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// Workload lifecycle
	ApplyWorkload(context.Context, *ApplyWorkloadRequest) (*ApplyWorkloadResponse, error)
	DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error)
	// Retry trigger
	RetryWorkload(context.Context, *RetryWorkloadRequest) (*RetryWorkloadResponse, error)
	// Node management
	DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error)
	UndrainNode(context.Context, *UndrainNodeRequest) (*UndrainNodeResponse, error)
	TaintNode(context.Context, *TaintNodeRequest) (*TaintNodeResponse, error)
	UntaintNode(context.Context, *UntaintNodeRequest) (*UntaintNodeResponse, error)
	SetNodeLabel(context.Context, *SetNodeLabelRequest) (*SetNodeLabelResponse, error)
	DeleteNodeLabel(context.Context, *DeleteNodeLabelRequest) (*DeleteNodeLabelResponse, error)
	SubmitAutomationSuggestion(context.Context, *SubmitAutomationSuggestionRequest) (*SubmitAutomationSuggestionResponse, error)
	// Cluster and node management visibility
	ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error)
	GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error)
	GetClusterSummary(context.Context, *GetClusterSummaryRequest) (*GetClusterSummaryResponse, error)
	// Cluster-wide events: node joined, node lost, node left, workload
	// scheduled, drift detected, retries, reschedules, etc (see
	// internal/scheduler/events.go for producers). ListEvents is a
	// plain unary call (auto-bridged to REST by persys-gateway's
	// reflection-based grpcbridge, no gateway changes needed). WatchEvents
	// is a server-streaming call — grpcbridge explicitly does not bridge
	// streaming RPCs, so consumers that need HTTP (e.g. a browser
	// dashboard) go through a hand-written SSE endpoint on the gateway
	// instead of the generic bridge; a gRPC client (e.g. persysctl) can
	// call it directly.
	ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[SchedulerEventView]) error
	// Optional future streaming channel
	ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error
	// Standalone disk inventory (managed volumes)
	CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error)
	ListDisks(context.Context, *ListDisksRequest) (*ListDisksResponse, error)
	GetDisk(context.Context, *GetDiskRequest) (*GetDiskResponse, error)
	DeleteDisk(context.Context, *DeleteDiskRequest) (*DeleteDiskResponse, error)
	// Object storage (Ceph RGW / S3-compatible buckets)
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error)
	GetBucket(context.Context, *GetBucketRequest) (*GetBucketResponse, error)
	DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error)
	GetBucketAccess(context.Context, *GetBucketAccessRequest) (*GetBucketAccessResponse, error)
	ListBucketObjects(context.Context, *ListBucketObjectsRequest) (*ListBucketObjectsResponse, error)
	mustEmbedUnimplementedAgentControlServer()
}

// UnimplementedAgentControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentControlServer struct{}

func (UnimplementedAgentControlServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedAgentControlServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentControlServer) ApplyWorkload(context.Context, *ApplyWorkloadRequest) (*ApplyWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyWorkload not implemented")
}
func (UnimplementedAgentControlServer) DeleteWorkload(context.Context, *DeleteWorkloadRequest) (*DeleteWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkload not implemented")
}
func (UnimplementedAgentControlServer) RetryWorkload(context.Context, *RetryWorkloadRequest) (*RetryWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryWorkload not implemented")
}
func (UnimplementedAgentControlServer) DrainNode(context.Context, *DrainNodeRequest) (*DrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DrainNode not implemented")
}
func (UnimplementedAgentControlServer) UndrainNode(context.Context, *UndrainNodeRequest) (*UndrainNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UndrainNode not implemented")
}
func (UnimplementedAgentControlServer) TaintNode(context.Context, *TaintNodeRequest) (*TaintNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TaintNode not implemented")
}
func (UnimplementedAgentControlServer) UntaintNode(context.Context, *UntaintNodeRequest) (*UntaintNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UntaintNode not implemented")
}
func (UnimplementedAgentControlServer) SetNodeLabel(context.Context, *SetNodeLabelRequest) (*SetNodeLabelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetNodeLabel not implemented")
}
func (UnimplementedAgentControlServer) DeleteNodeLabel(context.Context, *DeleteNodeLabelRequest) (*DeleteNodeLabelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteNodeLabel not implemented")
}
func (UnimplementedAgentControlServer) SubmitAutomationSuggestion(context.Context, *SubmitAutomationSuggestionRequest) (*SubmitAutomationSuggestionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitAutomationSuggestion not implemented")
}
func (UnimplementedAgentControlServer) ListNodes(context.Context, *ListNodesRequest) (*ListNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNodes not implemented")
}
func (UnimplementedAgentControlServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedAgentControlServer) ListWorkloads(context.Context, *ListWorkloadsRequest) (*ListWorkloadsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkloads not implemented")
}
func (UnimplementedAgentControlServer) GetWorkload(context.Context, *GetWorkloadRequest) (*GetWorkloadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkload not implemented")
}
func (UnimplementedAgentControlServer) GetClusterSummary(context.Context, *GetClusterSummaryRequest) (*GetClusterSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterSummary not implemented")
}
func (UnimplementedAgentControlServer) ListEvents(context.Context, *ListEventsRequest) (*ListEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedAgentControlServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[SchedulerEventView]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedAgentControlServer) ControlStream(grpc.BidiStreamingServer[ControlMessage, ControlMessage]) error {
	return status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedAgentControlServer) CreateDisk(context.Context, *CreateDiskRequest) (*CreateDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDisk not implemented")
}
func (UnimplementedAgentControlServer) ListDisks(context.Context, *ListDisksRequest) (*ListDisksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDisks not implemented")
}
func (UnimplementedAgentControlServer) GetDisk(context.Context, *GetDiskRequest) (*GetDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDisk not implemented")
}
func (UnimplementedAgentControlServer) DeleteDisk(context.Context, *DeleteDiskRequest) (*DeleteDiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDisk not implemented")
}
func (UnimplementedAgentControlServer) CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedAgentControlServer) ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBuckets not implemented")
}
func (UnimplementedAgentControlServer) GetBucket(context.Context, *GetBucketRequest) (*GetBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucket not implemented")
}
func (UnimplementedAgentControlServer) DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedAgentControlServer) GetBucketAccess(context.Context, *GetBucketAccessRequest) (*GetBucketAccessResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBucketAccess not implemented")
}
func (UnimplementedAgentControlServer) ListBucketObjects(context.Context, *ListBucketObjectsRequest) (*ListBucketObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBucketObjects not implemented")
}
func (UnimplementedAgentControlServer) mustEmbedUnimplementedAgentControlServer() {}
func (UnimplementedAgentControlServer) testEmbeddedByValue()                      {}

// UnsafeAgentControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentControlServer will
// result in compilation errors.
type UnsafeAgentControlServer interface {
	mustEmbedUnimplementedAgentControlServer()
}

func RegisterAgentControlServer(s grpc.ServiceRegistrar, srv AgentControlServer) {
	// If the following call panics, it indicates UnimplementedAgentControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentControl_ServiceDesc, srv)
}

func _AgentControl_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ApplyWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ApplyWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ApplyWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ApplyWorkload(ctx, req.(*ApplyWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DeleteWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DeleteWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DeleteWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DeleteWorkload(ctx, req.(*DeleteWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_RetryWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).RetryWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_RetryWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).RetryWorkload(ctx, req.(*RetryWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DrainNode(ctx, req.(*DrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_UndrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UndrainNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).UndrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_UndrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).UndrainNode(ctx, req.(*UndrainNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_TaintNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaintNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).TaintNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_TaintNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).TaintNode(ctx, req.(*TaintNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_UntaintNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UntaintNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).UntaintNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_UntaintNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).UntaintNode(ctx, req.(*UntaintNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_SetNodeLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetNodeLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).SetNodeLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_SetNodeLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).SetNodeLabel(ctx, req.(*SetNodeLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DeleteNodeLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DeleteNodeLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DeleteNodeLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DeleteNodeLabel(ctx, req.(*DeleteNodeLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_SubmitAutomationSuggestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitAutomationSuggestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).SubmitAutomationSuggestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_SubmitAutomationSuggestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).SubmitAutomationSuggestion(ctx, req.(*SubmitAutomationSuggestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListNodes(ctx, req.(*ListNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListWorkloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListWorkloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListWorkloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListWorkloads(ctx, req.(*ListWorkloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetWorkload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetWorkload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetWorkload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetWorkload(ctx, req.(*GetWorkloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetClusterSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetClusterSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetClusterSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetClusterSummary(ctx, req.(*GetClusterSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListEvents(ctx, req.(*ListEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentControlServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, SchedulerEventView]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_WatchEventsServer = grpc.ServerStreamingServer[SchedulerEventView]

func _AgentControl_ControlStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentControlServer).ControlStream(&grpc.GenericServerStream[ControlMessage, ControlMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentControl_ControlStreamServer = grpc.BidiStreamingServer[ControlMessage, ControlMessage]

func _AgentControl_CreateDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).CreateDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_CreateDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).CreateDisk(ctx, req.(*CreateDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListDisks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDisksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListDisks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListDisks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListDisks(ctx, req.(*ListDisksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetDisk(ctx, req.(*GetDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DeleteDisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DeleteDisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DeleteDisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DeleteDisk(ctx, req.(*DeleteDiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListBuckets(ctx, req.(*ListBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetBucket(ctx, req.(*GetBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_GetBucketAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).GetBucketAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_GetBucketAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).GetBucketAccess(ctx, req.(*GetBucketAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentControl_ListBucketObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentControlServer).ListBucketObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentControl_ListBucketObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentControlServer).ListBucketObjects(ctx, req.(*ListBucketObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentControl_ServiceDesc is the grpc.ServiceDesc for AgentControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "persys.control.v1.AgentControl",
	HandlerType: (*AgentControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _AgentControl_RegisterNode_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentControl_Heartbeat_Handler,
		},
		{
			MethodName: "ApplyWorkload",
			Handler:    _AgentControl_ApplyWorkload_Handler,
		},
		{
			MethodName: "DeleteWorkload",
			Handler:    _AgentControl_DeleteWorkload_Handler,
		},
		{
			MethodName: "RetryWorkload",
			Handler:    _AgentControl_RetryWorkload_Handler,
		},
		{
			MethodName: "DrainNode",
			Handler:    _AgentControl_DrainNode_Handler,
		},
		{
			MethodName: "UndrainNode",
			Handler:    _AgentControl_UndrainNode_Handler,
		},
		{
			MethodName: "TaintNode",
			Handler:    _AgentControl_TaintNode_Handler,
		},
		{
			MethodName: "UntaintNode",
			Handler:    _AgentControl_UntaintNode_Handler,
		},
		{
			MethodName: "SetNodeLabel",
			Handler:    _AgentControl_SetNodeLabel_Handler,
		},
		{
			MethodName: "DeleteNodeLabel",
			Handler:    _AgentControl_DeleteNodeLabel_Handler,
		},
		{
			MethodName: "SubmitAutomationSuggestion",
			Handler:    _AgentControl_SubmitAutomationSuggestion_Handler,
		},
		{
			MethodName: "ListNodes",
			Handler:    _AgentControl_ListNodes_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _AgentControl_GetNode_Handler,
		},
		{
			MethodName: "ListWorkloads",
			Handler:    _AgentControl_ListWorkloads_Handler,
		},
		{
			MethodName: "GetWorkload",
			Handler:    _AgentControl_GetWorkload_Handler,
		},
		{
			MethodName: "GetClusterSummary",
			Handler:    _AgentControl_GetClusterSummary_Handler,
		},
		{
			MethodName: "ListEvents",
			Handler:    _AgentControl_ListEvents_Handler,
		},
		{
			MethodName: "CreateDisk",
			Handler:    _AgentControl_CreateDisk_Handler,
		},
		{
			MethodName: "ListDisks",
			Handler:    _AgentControl_ListDisks_Handler,
		},
		{
			MethodName: "GetDisk",
			Handler:    _AgentControl_GetDisk_Handler,
		},
		{
			MethodName: "DeleteDisk",
			Handler:    _AgentControl_DeleteDisk_Handler,
		},
		{
			MethodName: "CreateBucket",
			Handler:    _AgentControl_CreateBucket_Handler,
		},
		{
			MethodName: "ListBuckets",
			Handler:    _AgentControl_ListBuckets_Handler,
		},
		{
			MethodName: "GetBucket",
			Handler:    _AgentControl_GetBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _AgentControl_DeleteBucket_Handler,
		},
		{
			MethodName: "GetBucketAccess",
			Handler:    _AgentControl_GetBucketAccess_Handler,
		},
		{
			MethodName: "ListBucketObjects",
			Handler:    _AgentControl_ListBucketObjects_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _AgentControl_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ControlStream",
			Handler:       _AgentControl_ControlStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
