// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureReason int32

const (
	FailureReason_FAILURE_REASON_UNSPECIFIED FailureReason = 0
	FailureReason_IMAGE_PULL_FAILED          FailureReason = 1
	FailureReason_IMAGE_NOT_FOUND            FailureReason = 2
	FailureReason_INSUFFICIENT_RESOURCES     FailureReason = 3
	FailureReason_INVALID_SPEC               FailureReason = 4
	FailureReason_RUNTIME_ERROR              FailureReason = 5
	FailureReason_NETWORK_ERROR              FailureReason = 6
	FailureReason_STORAGE_ERROR              FailureReason = 7
	FailureReason_VM_BOOT_FAILED             FailureReason = 8
)

// Enum value maps for FailureReason.
var (
	FailureReason_name = map[int32]string{
		0: "FAILURE_REASON_UNSPECIFIED",
		1: "IMAGE_PULL_FAILED",
		2: "IMAGE_NOT_FOUND",
		3: "INSUFFICIENT_RESOURCES",
		4: "INVALID_SPEC",
		5: "RUNTIME_ERROR",
		6: "NETWORK_ERROR",
		7: "STORAGE_ERROR",
		8: "VM_BOOT_FAILED",
	}
	FailureReason_value = map[string]int32{
		"FAILURE_REASON_UNSPECIFIED": 0,
		"IMAGE_PULL_FAILED":          1,
		"IMAGE_NOT_FOUND":            2,
		"INSUFFICIENT_RESOURCES":     3,
		"INVALID_SPEC":               4,
		"RUNTIME_ERROR":              5,
		"NETWORK_ERROR":              6,
		"STORAGE_ERROR":              7,
		"VM_BOOT_FAILED":             8,
	}
)

func (x FailureReason) Enum() *FailureReason {
	p := new(FailureReason)
	*p = x
	return p
}

func (x FailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_control_proto_enumTypes[0].Descriptor()
}

func (FailureReason) Type() protoreflect.EnumType {
	return &file_control_proto_enumTypes[0]
}

func (x FailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureReason.Descriptor instead.
func (FailureReason) EnumDescriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Capabilities  *NodeCapabilities      `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AgentVersion  string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	GrpcEndpoint  string                 `protobuf:"bytes,5,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	ClusterId     string                 `protobuf:"bytes,6,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetCapabilities() *NodeCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterNodeRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *RegisterNodeRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterNodeRequest) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *RegisterNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterNodeRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NodeCapabilities struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuTotalMillicores     int64                  `protobuf:"varint,1,opt,name=cpu_total_millicores,json=cpuTotalMillicores,proto3" json:"cpu_total_millicores,omitempty"`
	MemoryTotalMb          int64                  `protobuf:"varint,2,opt,name=memory_total_mb,json=memoryTotalMb,proto3" json:"memory_total_mb,omitempty"`
	StoragePools           []*StoragePool         `protobuf:"bytes,3,rep,name=storage_pools,json=storagePools,proto3" json:"storage_pools,omitempty"`
	SupportedWorkloadTypes []string               `protobuf:"bytes,4,rep,name=supported_workload_types,json=supportedWorkloadTypes,proto3" json:"supported_workload_types,omitempty"` // container, compose, vm
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeCapabilities) Reset() {
	*x = NodeCapabilities{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCapabilities) ProtoMessage() {}

func (x *NodeCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCapabilities.ProtoReflect.Descriptor instead.
func (*NodeCapabilities) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *NodeCapabilities) GetCpuTotalMillicores() int64 {
	if x != nil {
		return x.CpuTotalMillicores
	}
	return 0
}

func (x *NodeCapabilities) GetMemoryTotalMb() int64 {
	if x != nil {
		return x.MemoryTotalMb
	}
	return 0
}

func (x *NodeCapabilities) GetStoragePools() []*StoragePool {
	if x != nil {
		return x.StoragePools
	}
	return nil
}

func (x *NodeCapabilities) GetSupportedWorkloadTypes() []string {
	if x != nil {
		return x.SupportedWorkloadTypes
	}
	return nil
}

type StoragePool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // local, nfs, iscsi
	TotalGb       int64                  `protobuf:"varint,3,opt,name=total_gb,json=totalGb,proto3" json:"total_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoragePool) Reset() {
	*x = StoragePool{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePool) ProtoMessage() {}

func (x *StoragePool) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePool.ProtoReflect.Descriptor instead.
func (*StoragePool) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *StoragePool) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoragePool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *StoragePool) GetTotalGb() int64 {
	if x != nil {
		return x.TotalGb
	}
	return 0
}

type RegisterNodeResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Accepted                 bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason                   string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	HeartbeatIntervalSeconds int32                  `protobuf:"varint,3,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	LeaseExpiresAt           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterNodeResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RegisterNodeResponse) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *RegisterNodeResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type HeartbeatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Usage            *NodeUsage             `protobuf:"bytes,2,opt,name=usage,proto3" json:"usage,omitempty"`
	WorkloadStatuses []*WorkloadStatus      `protobuf:"bytes,3,rep,name=workload_statuses,json=workloadStatuses,proto3" json:"workload_statuses,omitempty"`
	Timestamp        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetUsage() *NodeUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *HeartbeatRequest) GetWorkloadStatuses() []*WorkloadStatus {
	if x != nil {
		return x.WorkloadStatuses
	}
	return nil
}

func (x *HeartbeatRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type NodeUsage struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CpuAllocatedMillicores int64                  `protobuf:"varint,1,opt,name=cpu_allocated_millicores,json=cpuAllocatedMillicores,proto3" json:"cpu_allocated_millicores,omitempty"`
	CpuUsedMillicores      int64                  `protobuf:"varint,2,opt,name=cpu_used_millicores,json=cpuUsedMillicores,proto3" json:"cpu_used_millicores,omitempty"`
	MemoryAllocatedMb      int64                  `protobuf:"varint,3,opt,name=memory_allocated_mb,json=memoryAllocatedMb,proto3" json:"memory_allocated_mb,omitempty"`
	MemoryUsedMb           int64                  `protobuf:"varint,4,opt,name=memory_used_mb,json=memoryUsedMb,proto3" json:"memory_used_mb,omitempty"`
	DiskAllocatedGb        int64                  `protobuf:"varint,5,opt,name=disk_allocated_gb,json=diskAllocatedGb,proto3" json:"disk_allocated_gb,omitempty"`
	DiskUsedGb             int64                  `protobuf:"varint,6,opt,name=disk_used_gb,json=diskUsedGb,proto3" json:"disk_used_gb,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeUsage) Reset() {
	*x = NodeUsage{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeUsage) ProtoMessage() {}

func (x *NodeUsage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeUsage.ProtoReflect.Descriptor instead.
func (*NodeUsage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *NodeUsage) GetCpuAllocatedMillicores() int64 {
	if x != nil {
		return x.CpuAllocatedMillicores
	}
	return 0
}

func (x *NodeUsage) GetCpuUsedMillicores() int64 {
	if x != nil {
		return x.CpuUsedMillicores
	}
	return 0
}

func (x *NodeUsage) GetMemoryAllocatedMb() int64 {
	if x != nil {
		return x.MemoryAllocatedMb
	}
	return 0
}

func (x *NodeUsage) GetMemoryUsedMb() int64 {
	if x != nil {
		return x.MemoryUsedMb
	}
	return 0
}

func (x *NodeUsage) GetDiskAllocatedGb() int64 {
	if x != nil {
		return x.DiskAllocatedGb
	}
	return 0
}

func (x *NodeUsage) GetDiskUsedGb() int64 {
	if x != nil {
		return x.DiskUsedGb
	}
	return 0
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged   bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	DrainNode      bool                   `protobuf:"varint,2,opt,name=drain_node,json=drainNode,proto3" json:"drain_node,omitempty"`
	LeaseExpiresAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetDrainNode() bool {
	if x != nil {
		return x.DrainNode
	}
	return false
}

func (x *HeartbeatResponse) GetLeaseExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return nil
}

type ApplyWorkloadRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Spec       *WorkloadSpec          `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Compatibility fields aligned with existing agent apply semantics.
	RevisionId    string `protobuf:"bytes,10,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	DesiredState  string `protobuf:"bytes,11,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"` // Running | Stopped
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWorkloadRequest) Reset() {
	*x = ApplyWorkloadRequest{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWorkloadRequest) ProtoMessage() {}

func (x *ApplyWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWorkloadRequest.ProtoReflect.Descriptor instead.
func (*ApplyWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *ApplyWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *ApplyWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *ApplyWorkloadRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *ApplyWorkloadRequest) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

type ApplyWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	FailureReason FailureReason          `protobuf:"varint,2,opt,name=failure_reason,json=failureReason,proto3,enum=persys.control.v1.FailureReason" json:"failure_reason,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWorkloadResponse) Reset() {
	*x = ApplyWorkloadResponse{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWorkloadResponse) ProtoMessage() {}

func (x *ApplyWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWorkloadResponse.ProtoReflect.Descriptor instead.
func (*ApplyWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyWorkloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyWorkloadResponse) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *ApplyWorkloadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DeleteWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadRequest) Reset() {
	*x = DeleteWorkloadRequest{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadRequest) ProtoMessage() {}

func (x *DeleteWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

type DeleteWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadResponse) Reset() {
	*x = DeleteWorkloadResponse{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadResponse) ProtoMessage() {}

func (x *DeleteWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteWorkloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWorkloadResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WorkloadSpec struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // container, compose, vm
	Resources *ResourceRequirements  `protobuf:"bytes,2,opt,name=resources,proto3" json:"resources,omitempty"`
	// Types that are valid to be assigned to Workload:
	//
	//	*WorkloadSpec_Container
	//	*WorkloadSpec_Compose
	//	*WorkloadSpec_Vm
	Workload      isWorkloadSpec_Workload `protobuf_oneof:"workload"`
	Metadata      map[string]string       `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *WorkloadSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkloadSpec) GetResources() *ResourceRequirements {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *WorkloadSpec) GetWorkload() isWorkloadSpec_Workload {
	if x != nil {
		return x.Workload
	}
	return nil
}

func (x *WorkloadSpec) GetContainer() *ContainerSpec {
	if x != nil {
		if x, ok := x.Workload.(*WorkloadSpec_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *WorkloadSpec) GetCompose() *ComposeSpec {
	if x != nil {
		if x, ok := x.Workload.(*WorkloadSpec_Compose); ok {
			return x.Compose
		}
	}
	return nil
}

func (x *WorkloadSpec) GetVm() *VMSpec {
	if x != nil {
		if x, ok := x.Workload.(*WorkloadSpec_Vm); ok {
			return x.Vm
		}
	}
	return nil
}

func (x *WorkloadSpec) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isWorkloadSpec_Workload interface {
	isWorkloadSpec_Workload()
}

type WorkloadSpec_Container struct {
	Container *ContainerSpec `protobuf:"bytes,10,opt,name=container,proto3,oneof"`
}

type WorkloadSpec_Compose struct {
	Compose *ComposeSpec `protobuf:"bytes,11,opt,name=compose,proto3,oneof"`
}

type WorkloadSpec_Vm struct {
	Vm *VMSpec `protobuf:"bytes,12,opt,name=vm,proto3,oneof"`
}

func (*WorkloadSpec_Container) isWorkloadSpec_Workload() {}

func (*WorkloadSpec_Compose) isWorkloadSpec_Workload() {}

func (*WorkloadSpec_Vm) isWorkloadSpec_Workload() {}

type ResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuMillicores int64                  `protobuf:"varint,1,opt,name=cpu_millicores,json=cpuMillicores,proto3" json:"cpu_millicores,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb        int64                  `protobuf:"varint,3,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *ResourceRequirements) GetCpuMillicores() int64 {
	if x != nil {
		return x.CpuMillicores
	}
	return 0
}

func (x *ResourceRequirements) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *ResourceRequirements) GetDiskGb() int64 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Volumes       []*VolumeMount         `protobuf:"bytes,4,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Ports         []*Port                `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,6,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	Privileged    bool                   `protobuf:"varint,7,opt,name=privileged,proto3" json:"privileged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ContainerSpec) GetPorts() []*Port {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

func (x *ContainerSpec) GetPrivileged() bool {
	if x != nil {
		return x.Privileged
	}
	return false
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	ContainerPath string                 `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *VolumeMount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *VolumeMount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type Port struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      int32                  `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp or udp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Port.ProtoReflect.Descriptor instead.
func (*Port) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *Port) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *Port) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *Port) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ComposeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceType    string                 `protobuf:"bytes,1,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // git or inline
	GitRepo       string                 `protobuf:"bytes,2,opt,name=git_repo,json=gitRepo,proto3" json:"git_repo,omitempty"`
	GitRef        string                 `protobuf:"bytes,3,opt,name=git_ref,json=gitRef,proto3" json:"git_ref,omitempty"`
	InlineYaml    string                 `protobuf:"bytes,4,opt,name=inline_yaml,json=inlineYaml,proto3" json:"inline_yaml,omitempty"`
	Env           map[string]string      `protobuf:"bytes,5,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeSpec) Reset() {
	*x = ComposeSpec{}
	mi := &file_control_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeSpec) ProtoMessage() {}

func (x *ComposeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeSpec.ProtoReflect.Descriptor instead.
func (*ComposeSpec) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{16}
}

func (x *ComposeSpec) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *ComposeSpec) GetGitRepo() string {
	if x != nil {
		return x.GitRepo
	}
	return ""
}

func (x *ComposeSpec) GetGitRef() string {
	if x != nil {
		return x.GitRef
	}
	return ""
}

func (x *ComposeSpec) GetInlineYaml() string {
	if x != nil {
		return x.InlineYaml
	}
	return ""
}

func (x *ComposeSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type VMSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vcpus         int32                  `protobuf:"varint,1,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb      int64                  `protobuf:"varint,2,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Disks         []*DiskConfig          `protobuf:"bytes,3,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks      []*NetworkConfig       `protobuf:"bytes,4,rep,name=networks,proto3" json:"networks,omitempty"`
	CloudInit     *CloudInitConfig       `protobuf:"bytes,5,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"`
	OsImage       string                 `protobuf:"bytes,6,opt,name=os_image,json=osImage,proto3" json:"os_image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMSpec) Reset() {
	*x = VMSpec{}
	mi := &file_control_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSpec) ProtoMessage() {}

func (x *VMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSpec.ProtoReflect.Descriptor instead.
func (*VMSpec) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{17}
}

func (x *VMSpec) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMSpec) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMSpec) GetDisks() []*DiskConfig {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VMSpec) GetNetworks() []*NetworkConfig {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *VMSpec) GetCloudInit() *CloudInitConfig {
	if x != nil {
		return x.CloudInit
	}
	return nil
}

func (x *VMSpec) GetOsImage() string {
	if x != nil {
		return x.OsImage
	}
	return ""
}

type DiskConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolName      string                 `protobuf:"bytes,1,opt,name=pool_name,json=poolName,proto3" json:"pool_name,omitempty"`
	SizeGb        int64                  `protobuf:"varint,2,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	MountPoint    string                 `protobuf:"bytes,3,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskConfig) Reset() {
	*x = DiskConfig{}
	mi := &file_control_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskConfig) ProtoMessage() {}

func (x *DiskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskConfig.ProtoReflect.Descriptor instead.
func (*DiskConfig) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{18}
}

func (x *DiskConfig) GetPoolName() string {
	if x != nil {
		return x.PoolName
	}
	return ""
}

func (x *DiskConfig) GetSizeGb() int64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

func (x *DiskConfig) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bridge        string                 `protobuf:"bytes,1,opt,name=bridge,proto3" json:"bridge,omitempty"`
	Dhcp          bool                   `protobuf:"varint,2,opt,name=dhcp,proto3" json:"dhcp,omitempty"`
	StaticIp      string                 `protobuf:"bytes,3,opt,name=static_ip,json=staticIp,proto3" json:"static_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_control_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{19}
}

func (x *NetworkConfig) GetBridge() string {
	if x != nil {
		return x.Bridge
	}
	return ""
}

func (x *NetworkConfig) GetDhcp() bool {
	if x != nil {
		return x.Dhcp
	}
	return false
}

func (x *NetworkConfig) GetStaticIp() string {
	if x != nil {
		return x.StaticIp
	}
	return ""
}

type CloudInitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      string                 `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	MetaData      string                 `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`
	NetworkConfig string                 `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInitConfig) Reset() {
	*x = CloudInitConfig{}
	mi := &file_control_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInitConfig) ProtoMessage() {}

func (x *CloudInitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInitConfig.ProtoReflect.Descriptor instead.
func (*CloudInitConfig) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{20}
}

func (x *CloudInitConfig) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *CloudInitConfig) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *CloudInitConfig) GetNetworkConfig() string {
	if x != nil {
		return x.NetworkConfig
	}
	return ""
}

type WorkloadStatus struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId     string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	State          string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // Running, Stopped, Failed
	FailureReason  FailureReason          `protobuf:"varint,3,opt,name=failure_reason,json=failureReason,proto3,enum=persys.control.v1.FailureReason" json:"failure_reason,omitempty"`
	Message        string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransition *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition,json=lastTransition,proto3" json:"last_transition,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_control_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{21}
}

func (x *WorkloadStatus) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *WorkloadStatus) GetFailureReason() FailureReason {
	if x != nil {
		return x.FailureReason
	}
	return FailureReason_FAILURE_REASON_UNSPECIFIED
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetLastTransition() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransition
	}
	return nil
}

type RetryWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWorkloadRequest) Reset() {
	*x = RetryWorkloadRequest{}
	mi := &file_control_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWorkloadRequest) ProtoMessage() {}

func (x *RetryWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWorkloadRequest.ProtoReflect.Descriptor instead.
func (*RetryWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{22}
}

func (x *RetryWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

type RetryWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryWorkloadResponse) Reset() {
	*x = RetryWorkloadResponse{}
	mi := &file_control_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryWorkloadResponse) ProtoMessage() {}

func (x *RetryWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryWorkloadResponse.ProtoReflect.Descriptor instead.
func (*RetryWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{23}
}

func (x *RetryWorkloadResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // optional filter: Ready | NotReady | Draining
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_control_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{24}
}

func (x *ListNodesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_control_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{25}
}

func (x *GetNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeView            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_control_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{26}
}

func (x *ListNodesResponse) GetNodes() []*NodeView {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeView              `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_control_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{27}
}

func (x *GetNodeResponse) GetNode() *NodeView {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeView struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	NodeId                 string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status                 string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	StatusReason           string                 `protobuf:"bytes,3,opt,name=status_reason,json=statusReason,proto3" json:"status_reason,omitempty"`
	StatusUpdatedBy        string                 `protobuf:"bytes,4,opt,name=status_updated_by,json=statusUpdatedBy,proto3" json:"status_updated_by,omitempty"`
	StatusUpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=status_updated_at,json=statusUpdatedAt,proto3" json:"status_updated_at,omitempty"`
	LastHeartbeat          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	GrpcEndpoint           string                 `protobuf:"bytes,7,opt,name=grpc_endpoint,json=grpcEndpoint,proto3" json:"grpc_endpoint,omitempty"`
	TotalCpuCores          float64                `protobuf:"fixed64,8,opt,name=total_cpu_cores,json=totalCpuCores,proto3" json:"total_cpu_cores,omitempty"`
	AvailableCpuCores      float64                `protobuf:"fixed64,9,opt,name=available_cpu_cores,json=availableCpuCores,proto3" json:"available_cpu_cores,omitempty"`
	TotalMemoryMb          int64                  `protobuf:"varint,10,opt,name=total_memory_mb,json=totalMemoryMb,proto3" json:"total_memory_mb,omitempty"`
	AvailableMemoryMb      int64                  `protobuf:"varint,11,opt,name=available_memory_mb,json=availableMemoryMb,proto3" json:"available_memory_mb,omitempty"`
	SupportedWorkloadTypes []string               `protobuf:"bytes,12,rep,name=supported_workload_types,json=supportedWorkloadTypes,proto3" json:"supported_workload_types,omitempty"`
	Labels                 map[string]string      `protobuf:"bytes,13,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeView) Reset() {
	*x = NodeView{}
	mi := &file_control_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeView) ProtoMessage() {}

func (x *NodeView) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeView.ProtoReflect.Descriptor instead.
func (*NodeView) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{28}
}

func (x *NodeView) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeView) GetStatusReason() string {
	if x != nil {
		return x.StatusReason
	}
	return ""
}

func (x *NodeView) GetStatusUpdatedBy() string {
	if x != nil {
		return x.StatusUpdatedBy
	}
	return ""
}

func (x *NodeView) GetStatusUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusUpdatedAt
	}
	return nil
}

func (x *NodeView) GetLastHeartbeat() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeat
	}
	return nil
}

func (x *NodeView) GetGrpcEndpoint() string {
	if x != nil {
		return x.GrpcEndpoint
	}
	return ""
}

func (x *NodeView) GetTotalCpuCores() float64 {
	if x != nil {
		return x.TotalCpuCores
	}
	return 0
}

func (x *NodeView) GetAvailableCpuCores() float64 {
	if x != nil {
		return x.AvailableCpuCores
	}
	return 0
}

func (x *NodeView) GetTotalMemoryMb() int64 {
	if x != nil {
		return x.TotalMemoryMb
	}
	return 0
}

func (x *NodeView) GetAvailableMemoryMb() int64 {
	if x != nil {
		return x.AvailableMemoryMb
	}
	return 0
}

func (x *NodeView) GetSupportedWorkloadTypes() []string {
	if x != nil {
		return x.SupportedWorkloadTypes
	}
	return nil
}

func (x *NodeView) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`               // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_control_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{29}
}

func (x *ListWorkloadsRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ListWorkloadsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadRequest) Reset() {
	*x = GetWorkloadRequest{}
	mi := &file_control_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadRequest) ProtoMessage() {}

func (x *GetWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{30}
}

func (x *GetWorkloadRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadView        `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_control_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{31}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*WorkloadView {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type GetWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workload      *WorkloadView          `protobuf:"bytes,1,opt,name=workload,proto3" json:"workload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadResponse) Reset() {
	*x = GetWorkloadResponse{}
	mi := &file_control_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadResponse) ProtoMessage() {}

func (x *GetWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{32}
}

func (x *GetWorkloadResponse) GetWorkload() *WorkloadView {
	if x != nil {
		return x.Workload
	}
	return nil
}

type WorkloadView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId       string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	Type             string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	DesiredState     string                 `protobuf:"bytes,3,opt,name=desired_state,json=desiredState,proto3" json:"desired_state,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AssignedNodeId   string                 `protobuf:"bytes,5,opt,name=assigned_node_id,json=assignedNodeId,proto3" json:"assigned_node_id,omitempty"`
	RevisionId       string                 `protobuf:"bytes,6,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	RetryAttempts    int32                  `protobuf:"varint,7,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	RetryMaxAttempts int32                  `protobuf:"varint,8,opt,name=retry_max_attempts,json=retryMaxAttempts,proto3" json:"retry_max_attempts,omitempty"`
	RetryNextAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=retry_next_at,json=retryNextAt,proto3" json:"retry_next_at,omitempty"`
	FailureReason    string                 `protobuf:"bytes,10,opt,name=failure_reason,json=failureReason,proto3" json:"failure_reason,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkloadView) Reset() {
	*x = WorkloadView{}
	mi := &file_control_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadView) ProtoMessage() {}

func (x *WorkloadView) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadView.ProtoReflect.Descriptor instead.
func (*WorkloadView) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{33}
}

func (x *WorkloadView) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *WorkloadView) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkloadView) GetDesiredState() string {
	if x != nil {
		return x.DesiredState
	}
	return ""
}

func (x *WorkloadView) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkloadView) GetAssignedNodeId() string {
	if x != nil {
		return x.AssignedNodeId
	}
	return ""
}

func (x *WorkloadView) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *WorkloadView) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *WorkloadView) GetRetryMaxAttempts() int32 {
	if x != nil {
		return x.RetryMaxAttempts
	}
	return 0
}

func (x *WorkloadView) GetRetryNextAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RetryNextAt
	}
	return nil
}

func (x *WorkloadView) GetFailureReason() string {
	if x != nil {
		return x.FailureReason
	}
	return ""
}

func (x *WorkloadView) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

type GetClusterSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterSummaryRequest) Reset() {
	*x = GetClusterSummaryRequest{}
	mi := &file_control_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterSummaryRequest) ProtoMessage() {}

func (x *GetClusterSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetClusterSummaryRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{34}
}

type GetClusterSummaryResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalNodes       int32                  `protobuf:"varint,1,opt,name=total_nodes,json=totalNodes,proto3" json:"total_nodes,omitempty"`
	ReadyNodes       int32                  `protobuf:"varint,2,opt,name=ready_nodes,json=readyNodes,proto3" json:"ready_nodes,omitempty"`
	NotReadyNodes    int32                  `protobuf:"varint,3,opt,name=not_ready_nodes,json=notReadyNodes,proto3" json:"not_ready_nodes,omitempty"`
	TotalWorkloads   int32                  `protobuf:"varint,4,opt,name=total_workloads,json=totalWorkloads,proto3" json:"total_workloads,omitempty"`
	RunningWorkloads int32                  `protobuf:"varint,5,opt,name=running_workloads,json=runningWorkloads,proto3" json:"running_workloads,omitempty"`
	PendingWorkloads int32                  `protobuf:"varint,6,opt,name=pending_workloads,json=pendingWorkloads,proto3" json:"pending_workloads,omitempty"`
	FailedWorkloads  int32                  `protobuf:"varint,7,opt,name=failed_workloads,json=failedWorkloads,proto3" json:"failed_workloads,omitempty"`
	DeletedWorkloads int32                  `protobuf:"varint,8,opt,name=deleted_workloads,json=deletedWorkloads,proto3" json:"deleted_workloads,omitempty"`
	GeneratedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetClusterSummaryResponse) Reset() {
	*x = GetClusterSummaryResponse{}
	mi := &file_control_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterSummaryResponse) ProtoMessage() {}

func (x *GetClusterSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetClusterSummaryResponse) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{35}
}

func (x *GetClusterSummaryResponse) GetTotalNodes() int32 {
	if x != nil {
		return x.TotalNodes
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetReadyNodes() int32 {
	if x != nil {
		return x.ReadyNodes
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetNotReadyNodes() int32 {
	if x != nil {
		return x.NotReadyNodes
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetTotalWorkloads() int32 {
	if x != nil {
		return x.TotalWorkloads
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetRunningWorkloads() int32 {
	if x != nil {
		return x.RunningWorkloads
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetPendingWorkloads() int32 {
	if x != nil {
		return x.PendingWorkloads
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetFailedWorkloads() int32 {
	if x != nil {
		return x.FailedWorkloads
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetDeletedWorkloads() int32 {
	if x != nil {
		return x.DeletedWorkloads
	}
	return 0
}

func (x *GetClusterSummaryResponse) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

type ControlMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ControlMessage_Register
	//	*ControlMessage_Heartbeat
	//	*ControlMessage_Apply
	//	*ControlMessage_Delete
	Message       isControlMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_control_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{36}
}

func (x *ControlMessage) GetMessage() isControlMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ControlMessage) GetRegister() *RegisterNodeRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *ControlMessage) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ControlMessage) GetApply() *ApplyWorkloadRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Apply); ok {
			return x.Apply
		}
	}
	return nil
}

func (x *ControlMessage) GetDelete() *DeleteWorkloadRequest {
	if x != nil {
		if x, ok := x.Message.(*ControlMessage_Delete); ok {
			return x.Delete
		}
	}
	return nil
}

type isControlMessage_Message interface {
	isControlMessage_Message()
}

type ControlMessage_Register struct {
	Register *RegisterNodeRequest `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type ControlMessage_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type ControlMessage_Apply struct {
	Apply *ApplyWorkloadRequest `protobuf:"bytes,3,opt,name=apply,proto3,oneof"`
}

type ControlMessage_Delete struct {
	Delete *DeleteWorkloadRequest `protobuf:"bytes,4,opt,name=delete,proto3,oneof"`
}

func (*ControlMessage_Register) isControlMessage_Message() {}

func (*ControlMessage_Heartbeat) isControlMessage_Message() {}

func (*ControlMessage_Apply) isControlMessage_Message() {}

func (*ControlMessage_Delete) isControlMessage_Message() {}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\x11persys.control.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12G\n" +
	"\fcapabilities\x18\x02 \x01(\v2#.persys.control.v1.NodeCapabilitiesR\fcapabilities\x12J\n" +
	"\x06labels\x18\x03 \x03(\v22.persys.control.v1.RegisterNodeRequest.LabelsEntryR\x06labels\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12#\n" +
	"\rgrpc_endpoint\x18\x05 \x01(\tR\fgrpcEndpoint\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x06 \x01(\tR\tclusterId\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\x10NodeCapabilities\x120\n" +
	"\x14cpu_total_millicores\x18\x01 \x01(\x03R\x12cpuTotalMillicores\x12&\n" +
	"\x0fmemory_total_mb\x18\x02 \x01(\x03R\rmemoryTotalMb\x12C\n" +
	"\rstorage_pools\x18\x03 \x03(\v2\x1e.persys.control.v1.StoragePoolR\fstoragePools\x128\n" +
	"\x18supported_workload_types\x18\x04 \x03(\tR\x16supportedWorkloadTypes\"P\n" +
	"\vStoragePool\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x19\n" +
	"\btotal_gb\x18\x03 \x01(\x03R\atotalGb\"\xce\x01\n" +
	"\x14RegisterNodeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x03 \x01(\x05R\x18heartbeatIntervalSeconds\x12D\n" +
	"\x10lease_expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"\xe9\x01\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x122\n" +
	"\x05usage\x18\x02 \x01(\v2\x1c.persys.control.v1.NodeUsageR\x05usage\x12N\n" +
	"\x11workload_statuses\x18\x03 \x03(\v2!.persys.control.v1.WorkloadStatusR\x10workloadStatuses\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\x99\x02\n" +
	"\tNodeUsage\x128\n" +
	"\x18cpu_allocated_millicores\x18\x01 \x01(\x03R\x16cpuAllocatedMillicores\x12.\n" +
	"\x13cpu_used_millicores\x18\x02 \x01(\x03R\x11cpuUsedMillicores\x12.\n" +
	"\x13memory_allocated_mb\x18\x03 \x01(\x03R\x11memoryAllocatedMb\x12$\n" +
	"\x0ememory_used_mb\x18\x04 \x01(\x03R\fmemoryUsedMb\x12*\n" +
	"\x11disk_allocated_gb\x18\x05 \x01(\x03R\x0fdiskAllocatedGb\x12 \n" +
	"\fdisk_used_gb\x18\x06 \x01(\x03R\n" +
	"diskUsedGb\"\x9c\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12\x1d\n" +
	"\n" +
	"drain_node\x18\x02 \x01(\bR\tdrainNode\x12D\n" +
	"\x10lease_expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0eleaseExpiresAt\"\xb2\x01\n" +
	"\x14ApplyWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x123\n" +
	"\x04spec\x18\x02 \x01(\v2\x1f.persys.control.v1.WorkloadSpecR\x04spec\x12\x1f\n" +
	"\vrevision_id\x18\n" +
	" \x01(\tR\n" +
	"revisionId\x12#\n" +
	"\rdesired_state\x18\v \x01(\tR\fdesiredState\"\x9f\x01\n" +
	"\x15ApplyWorkloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12G\n" +
	"\x0efailure_reason\x18\x02 \x01(\x0e2 .persys.control.v1.FailureReasonR\rfailureReason\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"8\n" +
	"\x15DeleteWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\"W\n" +
	"\x16DeleteWorkloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa8\x03\n" +
	"\fWorkloadSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12E\n" +
	"\tresources\x18\x02 \x01(\v2'.persys.control.v1.ResourceRequirementsR\tresources\x12@\n" +
	"\tcontainer\x18\n" +
	" \x01(\v2 .persys.control.v1.ContainerSpecH\x00R\tcontainer\x12:\n" +
	"\acompose\x18\v \x01(\v2\x1e.persys.control.v1.ComposeSpecH\x00R\acompose\x12+\n" +
	"\x02vm\x18\f \x01(\v2\x19.persys.control.v1.VMSpecH\x00R\x02vm\x12I\n" +
	"\bmetadata\x18\x14 \x03(\v2-.persys.control.v1.WorkloadSpec.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\n" +
	"\n" +
	"\bworkload\"s\n" +
	"\x14ResourceRequirements\x12%\n" +
	"\x0ecpu_millicores\x18\x01 \x01(\x03R\rcpuMillicores\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x03 \x01(\x03R\x06diskGb\"\xe4\x02\n" +
	"\rContainerSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12;\n" +
	"\x03env\x18\x03 \x03(\v2).persys.control.v1.ContainerSpec.EnvEntryR\x03env\x128\n" +
	"\avolumes\x18\x04 \x03(\v2\x1e.persys.control.v1.VolumeMountR\avolumes\x12-\n" +
	"\x05ports\x18\x05 \x03(\v2\x17.persys.control.v1.PortR\x05ports\x12%\n" +
	"\x0erestart_policy\x18\x06 \x01(\tR\rrestartPolicy\x12\x1e\n" +
	"\n" +
	"privileged\x18\a \x01(\bR\n" +
	"privileged\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"n\n" +
	"\vVolumeMount\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"f\n" +
	"\x04Port\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\x05R\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\xf6\x01\n" +
	"\vComposeSpec\x12\x1f\n" +
	"\vsource_type\x18\x01 \x01(\tR\n" +
	"sourceType\x12\x19\n" +
	"\bgit_repo\x18\x02 \x01(\tR\agitRepo\x12\x17\n" +
	"\agit_ref\x18\x03 \x01(\tR\x06gitRef\x12\x1f\n" +
	"\vinline_yaml\x18\x04 \x01(\tR\n" +
	"inlineYaml\x129\n" +
	"\x03env\x18\x05 \x03(\v2'.persys.control.v1.ComposeSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8c\x02\n" +
	"\x06VMSpec\x12\x14\n" +
	"\x05vcpus\x18\x01 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x02 \x01(\x03R\bmemoryMb\x123\n" +
	"\x05disks\x18\x03 \x03(\v2\x1d.persys.control.v1.DiskConfigR\x05disks\x12<\n" +
	"\bnetworks\x18\x04 \x03(\v2 .persys.control.v1.NetworkConfigR\bnetworks\x12A\n" +
	"\n" +
	"cloud_init\x18\x05 \x01(\v2\".persys.control.v1.CloudInitConfigR\tcloudInit\x12\x19\n" +
	"\bos_image\x18\x06 \x01(\tR\aosImage\"c\n" +
	"\n" +
	"DiskConfig\x12\x1b\n" +
	"\tpool_name\x18\x01 \x01(\tR\bpoolName\x12\x17\n" +
	"\asize_gb\x18\x02 \x01(\x03R\x06sizeGb\x12\x1f\n" +
	"\vmount_point\x18\x03 \x01(\tR\n" +
	"mountPoint\"X\n" +
	"\rNetworkConfig\x12\x16\n" +
	"\x06bridge\x18\x01 \x01(\tR\x06bridge\x12\x12\n" +
	"\x04dhcp\x18\x02 \x01(\bR\x04dhcp\x12\x1b\n" +
	"\tstatic_ip\x18\x03 \x01(\tR\bstaticIp\"r\n" +
	"\x0fCloudInitConfig\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12\x1b\n" +
	"\tmeta_data\x18\x02 \x01(\tR\bmetaData\x12%\n" +
	"\x0enetwork_config\x18\x03 \x01(\tR\rnetworkConfig\"\xef\x01\n" +
	"\x0eWorkloadStatus\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12G\n" +
	"\x0efailure_reason\x18\x03 \x01(\x0e2 .persys.control.v1.FailureReasonR\rfailureReason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12C\n" +
	"\x0flast_transition\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0elastTransition\"7\n" +
	"\x14RetryWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\"3\n" +
	"\x15RetryWorkloadResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"*\n" +
	"\x10ListNodesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\")\n" +
	"\x0eGetNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"F\n" +
	"\x11ListNodesResponse\x121\n" +
	"\x05nodes\x18\x01 \x03(\v2\x1b.persys.control.v1.NodeViewR\x05nodes\"B\n" +
	"\x0fGetNodeResponse\x12/\n" +
	"\x04node\x18\x01 \x01(\v2\x1b.persys.control.v1.NodeViewR\x04node\"\xa2\x05\n" +
	"\bNodeView\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rstatus_reason\x18\x03 \x01(\tR\fstatusReason\x12*\n" +
	"\x11status_updated_by\x18\x04 \x01(\tR\x0fstatusUpdatedBy\x12F\n" +
	"\x11status_updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstatusUpdatedAt\x12A\n" +
	"\x0elast_heartbeat\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastHeartbeat\x12#\n" +
	"\rgrpc_endpoint\x18\a \x01(\tR\fgrpcEndpoint\x12&\n" +
	"\x0ftotal_cpu_cores\x18\b \x01(\x01R\rtotalCpuCores\x12.\n" +
	"\x13available_cpu_cores\x18\t \x01(\x01R\x11availableCpuCores\x12&\n" +
	"\x0ftotal_memory_mb\x18\n" +
	" \x01(\x03R\rtotalMemoryMb\x12.\n" +
	"\x13available_memory_mb\x18\v \x01(\x03R\x11availableMemoryMb\x128\n" +
	"\x18supported_workload_types\x18\f \x03(\tR\x16supportedWorkloadTypes\x12?\n" +
	"\x06labels\x18\r \x03(\v2'.persys.control.v1.NodeView.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14ListWorkloadsRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"5\n" +
	"\x12GetWorkloadRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\"V\n" +
	"\x15ListWorkloadsResponse\x12=\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1f.persys.control.v1.WorkloadViewR\tworkloads\"R\n" +
	"\x13GetWorkloadResponse\x12;\n" +
	"\bworkload\x18\x01 \x01(\v2\x1f.persys.control.v1.WorkloadViewR\bworkload\"\xc6\x03\n" +
	"\fWorkloadView\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rdesired_state\x18\x03 \x01(\tR\fdesiredState\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12(\n" +
	"\x10assigned_node_id\x18\x05 \x01(\tR\x0eassignedNodeId\x12\x1f\n" +
	"\vrevision_id\x18\x06 \x01(\tR\n" +
	"revisionId\x12%\n" +
	"\x0eretry_attempts\x18\a \x01(\x05R\rretryAttempts\x12,\n" +
	"\x12retry_max_attempts\x18\b \x01(\x05R\x10retryMaxAttempts\x12>\n" +
	"\rretry_next_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vretryNextAt\x12%\n" +
	"\x0efailure_reason\x18\n" +
	" \x01(\tR\rfailureReason\x12=\n" +
	"\flast_updated\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\"\x1a\n" +
	"\x18GetClusterSummaryRequest\"\x9f\x03\n" +
	"\x19GetClusterSummaryResponse\x12\x1f\n" +
	"\vtotal_nodes\x18\x01 \x01(\x05R\n" +
	"totalNodes\x12\x1f\n" +
	"\vready_nodes\x18\x02 \x01(\x05R\n" +
	"readyNodes\x12&\n" +
	"\x0fnot_ready_nodes\x18\x03 \x01(\x05R\rnotReadyNodes\x12'\n" +
	"\x0ftotal_workloads\x18\x04 \x01(\x05R\x0etotalWorkloads\x12+\n" +
	"\x11running_workloads\x18\x05 \x01(\x05R\x10runningWorkloads\x12+\n" +
	"\x11pending_workloads\x18\x06 \x01(\x05R\x10pendingWorkloads\x12)\n" +
	"\x10failed_workloads\x18\a \x01(\x05R\x0ffailedWorkloads\x12+\n" +
	"\x11deleted_workloads\x18\b \x01(\x05R\x10deletedWorkloads\x12=\n" +
	"\fgenerated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\"\xab\x02\n" +
	"\x0eControlMessage\x12D\n" +
	"\bregister\x18\x01 \x01(\v2&.persys.control.v1.RegisterNodeRequestH\x00R\bregister\x12C\n" +
	"\theartbeat\x18\x02 \x01(\v2#.persys.control.v1.HeartbeatRequestH\x00R\theartbeat\x12?\n" +
	"\x05apply\x18\x03 \x01(\v2'.persys.control.v1.ApplyWorkloadRequestH\x00R\x05apply\x12B\n" +
	"\x06delete\x18\x04 \x01(\v2(.persys.control.v1.DeleteWorkloadRequestH\x00R\x06deleteB\t\n" +
	"\amessage*\xd6\x01\n" +
	"\rFailureReason\x12\x1e\n" +
	"\x1aFAILURE_REASON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11IMAGE_PULL_FAILED\x10\x01\x12\x13\n" +
	"\x0fIMAGE_NOT_FOUND\x10\x02\x12\x1a\n" +
	"\x16INSUFFICIENT_RESOURCES\x10\x03\x12\x10\n" +
	"\fINVALID_SPEC\x10\x04\x12\x11\n" +
	"\rRUNTIME_ERROR\x10\x05\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x06\x12\x11\n" +
	"\rSTORAGE_ERROR\x10\a\x12\x12\n" +
	"\x0eVM_BOOT_FAILED\x10\b2\xad\b\n" +
	"\fAgentControl\x12_\n" +
	"\fRegisterNode\x12&.persys.control.v1.RegisterNodeRequest\x1a'.persys.control.v1.RegisterNodeResponse\x12V\n" +
	"\tHeartbeat\x12#.persys.control.v1.HeartbeatRequest\x1a$.persys.control.v1.HeartbeatResponse\x12b\n" +
	"\rApplyWorkload\x12'.persys.control.v1.ApplyWorkloadRequest\x1a(.persys.control.v1.ApplyWorkloadResponse\x12e\n" +
	"\x0eDeleteWorkload\x12(.persys.control.v1.DeleteWorkloadRequest\x1a).persys.control.v1.DeleteWorkloadResponse\x12b\n" +
	"\rRetryWorkload\x12'.persys.control.v1.RetryWorkloadRequest\x1a(.persys.control.v1.RetryWorkloadResponse\x12V\n" +
	"\tListNodes\x12#.persys.control.v1.ListNodesRequest\x1a$.persys.control.v1.ListNodesResponse\x12P\n" +
	"\aGetNode\x12!.persys.control.v1.GetNodeRequest\x1a\".persys.control.v1.GetNodeResponse\x12b\n" +
	"\rListWorkloads\x12'.persys.control.v1.ListWorkloadsRequest\x1a(.persys.control.v1.ListWorkloadsResponse\x12\\\n" +
	"\vGetWorkload\x12%.persys.control.v1.GetWorkloadRequest\x1a&.persys.control.v1.GetWorkloadResponse\x12n\n" +
	"\x11GetClusterSummary\x12+.persys.control.v1.GetClusterSummaryRequest\x1a,.persys.control.v1.GetClusterSummaryResponse\x12Y\n" +
	"\rControlStream\x12!.persys.control.v1.ControlMessage\x1a!.persys.control.v1.ControlMessage(\x010\x01B7Z5github.com/persys-dev/persys/api/control/v1;controlv1b\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_control_proto_goTypes = []any{
	(FailureReason)(0),                // 0: persys.control.v1.FailureReason
	(*RegisterNodeRequest)(nil),       // 1: persys.control.v1.RegisterNodeRequest
	(*NodeCapabilities)(nil),          // 2: persys.control.v1.NodeCapabilities
	(*StoragePool)(nil),               // 3: persys.control.v1.StoragePool
	(*RegisterNodeResponse)(nil),      // 4: persys.control.v1.RegisterNodeResponse
	(*HeartbeatRequest)(nil),          // 5: persys.control.v1.HeartbeatRequest
	(*NodeUsage)(nil),                 // 6: persys.control.v1.NodeUsage
	(*HeartbeatResponse)(nil),         // 7: persys.control.v1.HeartbeatResponse
	(*ApplyWorkloadRequest)(nil),      // 8: persys.control.v1.ApplyWorkloadRequest
	(*ApplyWorkloadResponse)(nil),     // 9: persys.control.v1.ApplyWorkloadResponse
	(*DeleteWorkloadRequest)(nil),     // 10: persys.control.v1.DeleteWorkloadRequest
	(*DeleteWorkloadResponse)(nil),    // 11: persys.control.v1.DeleteWorkloadResponse
	(*WorkloadSpec)(nil),              // 12: persys.control.v1.WorkloadSpec
	(*ResourceRequirements)(nil),      // 13: persys.control.v1.ResourceRequirements
	(*ContainerSpec)(nil),             // 14: persys.control.v1.ContainerSpec
	(*VolumeMount)(nil),               // 15: persys.control.v1.VolumeMount
	(*Port)(nil),                      // 16: persys.control.v1.Port
	(*ComposeSpec)(nil),               // 17: persys.control.v1.ComposeSpec
	(*VMSpec)(nil),                    // 18: persys.control.v1.VMSpec
	(*DiskConfig)(nil),                // 19: persys.control.v1.DiskConfig
	(*NetworkConfig)(nil),             // 20: persys.control.v1.NetworkConfig
	(*CloudInitConfig)(nil),           // 21: persys.control.v1.CloudInitConfig
	(*WorkloadStatus)(nil),            // 22: persys.control.v1.WorkloadStatus
	(*RetryWorkloadRequest)(nil),      // 23: persys.control.v1.RetryWorkloadRequest
	(*RetryWorkloadResponse)(nil),     // 24: persys.control.v1.RetryWorkloadResponse
	(*ListNodesRequest)(nil),          // 25: persys.control.v1.ListNodesRequest
	(*GetNodeRequest)(nil),            // 26: persys.control.v1.GetNodeRequest
	(*ListNodesResponse)(nil),         // 27: persys.control.v1.ListNodesResponse
	(*GetNodeResponse)(nil),           // 28: persys.control.v1.GetNodeResponse
	(*NodeView)(nil),                  // 29: persys.control.v1.NodeView
	(*ListWorkloadsRequest)(nil),      // 30: persys.control.v1.ListWorkloadsRequest
	(*GetWorkloadRequest)(nil),        // 31: persys.control.v1.GetWorkloadRequest
	(*ListWorkloadsResponse)(nil),     // 32: persys.control.v1.ListWorkloadsResponse
	(*GetWorkloadResponse)(nil),       // 33: persys.control.v1.GetWorkloadResponse
	(*WorkloadView)(nil),              // 34: persys.control.v1.WorkloadView
	(*GetClusterSummaryRequest)(nil),  // 35: persys.control.v1.GetClusterSummaryRequest
	(*GetClusterSummaryResponse)(nil), // 36: persys.control.v1.GetClusterSummaryResponse
	(*ControlMessage)(nil),            // 37: persys.control.v1.ControlMessage
	nil,                               // 38: persys.control.v1.RegisterNodeRequest.LabelsEntry
	nil,                               // 39: persys.control.v1.WorkloadSpec.MetadataEntry
	nil,                               // 40: persys.control.v1.ContainerSpec.EnvEntry
	nil,                               // 41: persys.control.v1.ComposeSpec.EnvEntry
	nil,                               // 42: persys.control.v1.NodeView.LabelsEntry
	(*timestamppb.Timestamp)(nil),     // 43: google.protobuf.Timestamp
}
var file_control_proto_depIdxs = []int32{
	2,  // 0: persys.control.v1.RegisterNodeRequest.capabilities:type_name -> persys.control.v1.NodeCapabilities
	38, // 1: persys.control.v1.RegisterNodeRequest.labels:type_name -> persys.control.v1.RegisterNodeRequest.LabelsEntry
	43, // 2: persys.control.v1.RegisterNodeRequest.timestamp:type_name -> google.protobuf.Timestamp
	3,  // 3: persys.control.v1.NodeCapabilities.storage_pools:type_name -> persys.control.v1.StoragePool
	43, // 4: persys.control.v1.RegisterNodeResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	6,  // 5: persys.control.v1.HeartbeatRequest.usage:type_name -> persys.control.v1.NodeUsage
	22, // 6: persys.control.v1.HeartbeatRequest.workload_statuses:type_name -> persys.control.v1.WorkloadStatus
	43, // 7: persys.control.v1.HeartbeatRequest.timestamp:type_name -> google.protobuf.Timestamp
	43, // 8: persys.control.v1.HeartbeatResponse.lease_expires_at:type_name -> google.protobuf.Timestamp
	12, // 9: persys.control.v1.ApplyWorkloadRequest.spec:type_name -> persys.control.v1.WorkloadSpec
	0,  // 10: persys.control.v1.ApplyWorkloadResponse.failure_reason:type_name -> persys.control.v1.FailureReason
	13, // 11: persys.control.v1.WorkloadSpec.resources:type_name -> persys.control.v1.ResourceRequirements
	14, // 12: persys.control.v1.WorkloadSpec.container:type_name -> persys.control.v1.ContainerSpec
	17, // 13: persys.control.v1.WorkloadSpec.compose:type_name -> persys.control.v1.ComposeSpec
	18, // 14: persys.control.v1.WorkloadSpec.vm:type_name -> persys.control.v1.VMSpec
	39, // 15: persys.control.v1.WorkloadSpec.metadata:type_name -> persys.control.v1.WorkloadSpec.MetadataEntry
	40, // 16: persys.control.v1.ContainerSpec.env:type_name -> persys.control.v1.ContainerSpec.EnvEntry
	15, // 17: persys.control.v1.ContainerSpec.volumes:type_name -> persys.control.v1.VolumeMount
	16, // 18: persys.control.v1.ContainerSpec.ports:type_name -> persys.control.v1.Port
	41, // 19: persys.control.v1.ComposeSpec.env:type_name -> persys.control.v1.ComposeSpec.EnvEntry
	19, // 20: persys.control.v1.VMSpec.disks:type_name -> persys.control.v1.DiskConfig
	20, // 21: persys.control.v1.VMSpec.networks:type_name -> persys.control.v1.NetworkConfig
	21, // 22: persys.control.v1.VMSpec.cloud_init:type_name -> persys.control.v1.CloudInitConfig
	0,  // 23: persys.control.v1.WorkloadStatus.failure_reason:type_name -> persys.control.v1.FailureReason
	43, // 24: persys.control.v1.WorkloadStatus.last_transition:type_name -> google.protobuf.Timestamp
	29, // 25: persys.control.v1.ListNodesResponse.nodes:type_name -> persys.control.v1.NodeView
	29, // 26: persys.control.v1.GetNodeResponse.node:type_name -> persys.control.v1.NodeView
	43, // 27: persys.control.v1.NodeView.status_updated_at:type_name -> google.protobuf.Timestamp
	43, // 28: persys.control.v1.NodeView.last_heartbeat:type_name -> google.protobuf.Timestamp
	42, // 29: persys.control.v1.NodeView.labels:type_name -> persys.control.v1.NodeView.LabelsEntry
	34, // 30: persys.control.v1.ListWorkloadsResponse.workloads:type_name -> persys.control.v1.WorkloadView
	34, // 31: persys.control.v1.GetWorkloadResponse.workload:type_name -> persys.control.v1.WorkloadView
	43, // 32: persys.control.v1.WorkloadView.retry_next_at:type_name -> google.protobuf.Timestamp
	43, // 33: persys.control.v1.WorkloadView.last_updated:type_name -> google.protobuf.Timestamp
	43, // 34: persys.control.v1.GetClusterSummaryResponse.generated_at:type_name -> google.protobuf.Timestamp
	1,  // 35: persys.control.v1.ControlMessage.register:type_name -> persys.control.v1.RegisterNodeRequest
	5,  // 36: persys.control.v1.ControlMessage.heartbeat:type_name -> persys.control.v1.HeartbeatRequest
	8,  // 37: persys.control.v1.ControlMessage.apply:type_name -> persys.control.v1.ApplyWorkloadRequest
	10, // 38: persys.control.v1.ControlMessage.delete:type_name -> persys.control.v1.DeleteWorkloadRequest
	1,  // 39: persys.control.v1.AgentControl.RegisterNode:input_type -> persys.control.v1.RegisterNodeRequest
	5,  // 40: persys.control.v1.AgentControl.Heartbeat:input_type -> persys.control.v1.HeartbeatRequest
	8,  // 41: persys.control.v1.AgentControl.ApplyWorkload:input_type -> persys.control.v1.ApplyWorkloadRequest
	10, // 42: persys.control.v1.AgentControl.DeleteWorkload:input_type -> persys.control.v1.DeleteWorkloadRequest
	23, // 43: persys.control.v1.AgentControl.RetryWorkload:input_type -> persys.control.v1.RetryWorkloadRequest
	25, // 44: persys.control.v1.AgentControl.ListNodes:input_type -> persys.control.v1.ListNodesRequest
	26, // 45: persys.control.v1.AgentControl.GetNode:input_type -> persys.control.v1.GetNodeRequest
	30, // 46: persys.control.v1.AgentControl.ListWorkloads:input_type -> persys.control.v1.ListWorkloadsRequest
	31, // 47: persys.control.v1.AgentControl.GetWorkload:input_type -> persys.control.v1.GetWorkloadRequest
	35, // 48: persys.control.v1.AgentControl.GetClusterSummary:input_type -> persys.control.v1.GetClusterSummaryRequest
	37, // 49: persys.control.v1.AgentControl.ControlStream:input_type -> persys.control.v1.ControlMessage
	4,  // 50: persys.control.v1.AgentControl.RegisterNode:output_type -> persys.control.v1.RegisterNodeResponse
	7,  // 51: persys.control.v1.AgentControl.Heartbeat:output_type -> persys.control.v1.HeartbeatResponse
	9,  // 52: persys.control.v1.AgentControl.ApplyWorkload:output_type -> persys.control.v1.ApplyWorkloadResponse
	11, // 53: persys.control.v1.AgentControl.DeleteWorkload:output_type -> persys.control.v1.DeleteWorkloadResponse
	24, // 54: persys.control.v1.AgentControl.RetryWorkload:output_type -> persys.control.v1.RetryWorkloadResponse
	27, // 55: persys.control.v1.AgentControl.ListNodes:output_type -> persys.control.v1.ListNodesResponse
	28, // 56: persys.control.v1.AgentControl.GetNode:output_type -> persys.control.v1.GetNodeResponse
	32, // 57: persys.control.v1.AgentControl.ListWorkloads:output_type -> persys.control.v1.ListWorkloadsResponse
	33, // 58: persys.control.v1.AgentControl.GetWorkload:output_type -> persys.control.v1.GetWorkloadResponse
	36, // 59: persys.control.v1.AgentControl.GetClusterSummary:output_type -> persys.control.v1.GetClusterSummaryResponse
	37, // 60: persys.control.v1.AgentControl.ControlStream:output_type -> persys.control.v1.ControlMessage
	50, // [50:61] is the sub-list for method output_type
	39, // [39:50] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[11].OneofWrappers = []any{
		(*WorkloadSpec_Container)(nil),
		(*WorkloadSpec_Compose)(nil),
		(*WorkloadSpec_Vm)(nil),
	}
	file_control_proto_msgTypes[36].OneofWrappers = []any{
		(*ControlMessage_Register)(nil),
		(*ControlMessage_Heartbeat)(nil),
		(*ControlMessage_Apply)(nil),
		(*ControlMessage_Delete)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		EnumInfos:         file_control_proto_enumTypes,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
