// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: cloud-mgmt.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServicesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID  int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	EventID int64 `protobuf:"varint,2,opt,name=eventID,proto3" json:"eventID,omitempty"`
}

func (x *ServicesRequest) Reset() {
	*x = ServicesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_mgmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesRequest) ProtoMessage() {}

func (x *ServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_mgmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesRequest.ProtoReflect.Descriptor instead.
func (*ServicesRequest) Descriptor() ([]byte, []int) {
	return file_cloud_mgmt_proto_rawDescGZIP(), []int{0}
}

func (x *ServicesRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ServicesRequest) GetEventID() int64 {
	if x != nil {
		return x.EventID
	}
	return 0
}

type ServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Persys string `protobuf:"bytes,2,opt,name=persys,proto3" json:"persys,omitempty"`
	Aws    string `protobuf:"bytes,3,opt,name=aws,proto3" json:"aws,omitempty"`
	Azure  string `protobuf:"bytes,4,opt,name=azure,proto3" json:"azure,omitempty"`
	Gcp    string `protobuf:"bytes,5,opt,name=gcp,proto3" json:"gcp,omitempty"`
	State  string `protobuf:"bytes,6,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cloud_mgmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_mgmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_cloud_mgmt_proto_rawDescGZIP(), []int{1}
}

func (x *ServicesResponse) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *ServicesResponse) GetPersys() string {
	if x != nil {
		return x.Persys
	}
	return ""
}

func (x *ServicesResponse) GetAws() string {
	if x != nil {
		return x.Aws
	}
	return ""
}

func (x *ServicesResponse) GetAzure() string {
	if x != nil {
		return x.Azure
	}
	return ""
}

func (x *ServicesResponse) GetGcp() string {
	if x != nil {
		return x.Gcp
	}
	return ""
}

func (x *ServicesResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

var File_cloud_mgmt_proto protoreflect.FileDescriptor

var file_cloud_mgmt_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x6d, 0x67, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x09, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x67, 0x6d, 0x74, 0x22, 0x43, 0x0a,
	0x0f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x22, 0x92, 0x01, 0x0a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x73, 0x79, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x70, 0x65, 0x72, 0x73, 0x79, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x77, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x7a, 0x75,
	0x72, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x67, 0x63, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x67, 0x63,
	0x70, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x32, 0x59, 0x0a, 0x10, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x4d, 0x67, 0x6d, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x08, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x4d,
	0x67, 0x6d, 0x74, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x4d, 0x67, 0x6d, 0x74, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cloud_mgmt_proto_rawDescOnce sync.Once
	file_cloud_mgmt_proto_rawDescData = file_cloud_mgmt_proto_rawDesc
)

func file_cloud_mgmt_proto_rawDescGZIP() []byte {
	file_cloud_mgmt_proto_rawDescOnce.Do(func() {
		file_cloud_mgmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_cloud_mgmt_proto_rawDescData)
	})
	return file_cloud_mgmt_proto_rawDescData
}

var file_cloud_mgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_cloud_mgmt_proto_goTypes = []interface{}{
	(*ServicesRequest)(nil),  // 0: cloudMgmt.servicesRequest
	(*ServicesResponse)(nil), // 1: cloudMgmt.servicesResponse
}
var file_cloud_mgmt_proto_depIdxs = []int32{
	0, // 0: cloudMgmt.CloudMgmtService.services:input_type -> cloudMgmt.servicesRequest
	1, // 1: cloudMgmt.CloudMgmtService.services:output_type -> cloudMgmt.servicesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cloud_mgmt_proto_init() }
func file_cloud_mgmt_proto_init() {
	if File_cloud_mgmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cloud_mgmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cloud_mgmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cloud_mgmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_mgmt_proto_goTypes,
		DependencyIndexes: file_cloud_mgmt_proto_depIdxs,
		MessageInfos:      file_cloud_mgmt_proto_msgTypes,
	}.Build()
	File_cloud_mgmt_proto = out.File
	file_cloud_mgmt_proto_rawDesc = nil
	file_cloud_mgmt_proto_goTypes = nil
	file_cloud_mgmt_proto_depIdxs = nil
}
