// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: vaultmanager.proto

package vaultmanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultManagerService_GetServiceCredentials_FullMethodName = "/vaultmanager.VaultManagerService/GetServiceCredentials"
	VaultManagerService_RotateServiceSecretID_FullMethodName = "/vaultmanager.VaultManagerService/RotateServiceSecretID"
)

// VaultManagerServiceClient is the client API for VaultManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VaultManagerServiceClient interface {
	GetServiceCredentials(ctx context.Context, in *GetServiceCredentialsRequest, opts ...grpc.CallOption) (*ServiceCredentialsResponse, error)
	RotateServiceSecretID(ctx context.Context, in *RotateServiceSecretIDRequest, opts ...grpc.CallOption) (*ServiceCredentialsResponse, error)
}

type vaultManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultManagerServiceClient(cc grpc.ClientConnInterface) VaultManagerServiceClient {
	return &vaultManagerServiceClient{cc}
}

func (c *vaultManagerServiceClient) GetServiceCredentials(ctx context.Context, in *GetServiceCredentialsRequest, opts ...grpc.CallOption) (*ServiceCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceCredentialsResponse)
	err := c.cc.Invoke(ctx, VaultManagerService_GetServiceCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultManagerServiceClient) RotateServiceSecretID(ctx context.Context, in *RotateServiceSecretIDRequest, opts ...grpc.CallOption) (*ServiceCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceCredentialsResponse)
	err := c.cc.Invoke(ctx, VaultManagerService_RotateServiceSecretID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultManagerServiceServer is the server API for VaultManagerService service.
// All implementations must embed UnimplementedVaultManagerServiceServer
// for forward compatibility.
type VaultManagerServiceServer interface {
	GetServiceCredentials(context.Context, *GetServiceCredentialsRequest) (*ServiceCredentialsResponse, error)
	RotateServiceSecretID(context.Context, *RotateServiceSecretIDRequest) (*ServiceCredentialsResponse, error)
	mustEmbedUnimplementedVaultManagerServiceServer()
}

// UnimplementedVaultManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultManagerServiceServer struct{}

func (UnimplementedVaultManagerServiceServer) GetServiceCredentials(context.Context, *GetServiceCredentialsRequest) (*ServiceCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceCredentials not implemented")
}
func (UnimplementedVaultManagerServiceServer) RotateServiceSecretID(context.Context, *RotateServiceSecretIDRequest) (*ServiceCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateServiceSecretID not implemented")
}
func (UnimplementedVaultManagerServiceServer) mustEmbedUnimplementedVaultManagerServiceServer() {}
func (UnimplementedVaultManagerServiceServer) testEmbeddedByValue()                             {}

// UnsafeVaultManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultManagerServiceServer will
// result in compilation errors.
type UnsafeVaultManagerServiceServer interface {
	mustEmbedUnimplementedVaultManagerServiceServer()
}

func RegisterVaultManagerServiceServer(s grpc.ServiceRegistrar, srv VaultManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultManagerService_ServiceDesc, srv)
}

func _VaultManagerService_GetServiceCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultManagerServiceServer).GetServiceCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultManagerService_GetServiceCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultManagerServiceServer).GetServiceCredentials(ctx, req.(*GetServiceCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultManagerService_RotateServiceSecretID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateServiceSecretIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultManagerServiceServer).RotateServiceSecretID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultManagerService_RotateServiceSecretID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultManagerServiceServer).RotateServiceSecretID(ctx, req.(*RotateServiceSecretIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultManagerService_ServiceDesc is the grpc.ServiceDesc for VaultManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vaultmanager.VaultManagerService",
	HandlerType: (*VaultManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceCredentials",
			Handler:    _VaultManagerService_GetServiceCredentials_Handler,
		},
		{
			MethodName: "RotateServiceSecretID",
			Handler:    _VaultManagerService_RotateServiceSecretID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vaultmanager.proto",
}
