// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: vaultmanager.proto

package vaultmanager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetServiceCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceCredentialsRequest) Reset() {
	*x = GetServiceCredentialsRequest{}
	mi := &file_vaultmanager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceCredentialsRequest) ProtoMessage() {}

func (x *GetServiceCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultmanager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetServiceCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_vaultmanager_proto_rawDescGZIP(), []int{0}
}

func (x *GetServiceCredentialsRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type RotateServiceSecretIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateServiceSecretIDRequest) Reset() {
	*x = RotateServiceSecretIDRequest{}
	mi := &file_vaultmanager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateServiceSecretIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateServiceSecretIDRequest) ProtoMessage() {}

func (x *RotateServiceSecretIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vaultmanager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateServiceSecretIDRequest.ProtoReflect.Descriptor instead.
func (*RotateServiceSecretIDRequest) Descriptor() ([]byte, []int) {
	return file_vaultmanager_proto_rawDescGZIP(), []int{1}
}

func (x *RotateServiceSecretIDRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

type ServiceCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleId        string                 `protobuf:"bytes,1,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	SecretId      string                 `protobuf:"bytes,2,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp seconds
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceCredentialsResponse) Reset() {
	*x = ServiceCredentialsResponse{}
	mi := &file_vaultmanager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceCredentialsResponse) ProtoMessage() {}

func (x *ServiceCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vaultmanager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ServiceCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_vaultmanager_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceCredentialsResponse) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *ServiceCredentialsResponse) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *ServiceCredentialsResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *ServiceCredentialsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_vaultmanager_proto protoreflect.FileDescriptor

const file_vaultmanager_proto_rawDesc = "" +
	"\n" +
	"\x12vaultmanager.proto\x12\fvaultmanager\"A\n" +
	"\x1cGetServiceCredentialsRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"A\n" +
	"\x1cRotateServiceSecretIDRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\"\x8b\x01\n" +
	"\x1aServiceCredentialsResponse\x12\x17\n" +
	"\arole_id\x18\x01 \x01(\tR\x06roleId\x12\x1b\n" +
	"\tsecret_id\x18\x02 \x01(\tR\bsecretId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage2\xf3\x01\n" +
	"\x13VaultManagerService\x12m\n" +
	"\x15GetServiceCredentials\x12*.vaultmanager.GetServiceCredentialsRequest\x1a(.vaultmanager.ServiceCredentialsResponse\x12m\n" +
	"\x15RotateServiceSecretID\x12*.vaultmanager.RotateServiceSecretIDRequest\x1a(.vaultmanager.ServiceCredentialsResponseB5Z3github.com/persys-dev/persys-cloud/pkg/vaultmanagerb\x06proto3"

var (
	file_vaultmanager_proto_rawDescOnce sync.Once
	file_vaultmanager_proto_rawDescData []byte
)

func file_vaultmanager_proto_rawDescGZIP() []byte {
	file_vaultmanager_proto_rawDescOnce.Do(func() {
		file_vaultmanager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vaultmanager_proto_rawDesc), len(file_vaultmanager_proto_rawDesc)))
	})
	return file_vaultmanager_proto_rawDescData
}

var file_vaultmanager_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_vaultmanager_proto_goTypes = []any{
	(*GetServiceCredentialsRequest)(nil), // 0: vaultmanager.GetServiceCredentialsRequest
	(*RotateServiceSecretIDRequest)(nil), // 1: vaultmanager.RotateServiceSecretIDRequest
	(*ServiceCredentialsResponse)(nil),   // 2: vaultmanager.ServiceCredentialsResponse
}
var file_vaultmanager_proto_depIdxs = []int32{
	0, // 0: vaultmanager.VaultManagerService.GetServiceCredentials:input_type -> vaultmanager.GetServiceCredentialsRequest
	1, // 1: vaultmanager.VaultManagerService.RotateServiceSecretID:input_type -> vaultmanager.RotateServiceSecretIDRequest
	2, // 2: vaultmanager.VaultManagerService.GetServiceCredentials:output_type -> vaultmanager.ServiceCredentialsResponse
	2, // 3: vaultmanager.VaultManagerService.RotateServiceSecretID:output_type -> vaultmanager.ServiceCredentialsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vaultmanager_proto_init() }
func file_vaultmanager_proto_init() {
	if File_vaultmanager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vaultmanager_proto_rawDesc), len(file_vaultmanager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vaultmanager_proto_goTypes,
		DependencyIndexes: file_vaultmanager_proto_depIdxs,
		MessageInfos:      file_vaultmanager_proto_msgTypes,
	}.Build()
	File_vaultmanager_proto = out.File
	file_vaultmanager_proto_goTypes = nil
	file_vaultmanager_proto_depIdxs = nil
}
