{
 "title": "etcd",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "etcd health",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by (instance) (delta(etcd_server_health_failures{}[$__rate_interval])) > bool 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd is leader",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_server_is_leader{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd active peers",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_network_active_peers{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd has leader",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_server_has_leader{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal write bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_disk_wal_write_bytes_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd leader changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(etcd_server_leader_changes_seen_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal fsync duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_disk_wal_fsync_duration_seconds_sum{}[$__rate_interval]) / rate(etcd_disk_wal_fsync_duration_seconds_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal fsync duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal fsync duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd wal write duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_disk_wal_write_duration_seconds_sum{}[$__rate_interval]) / rate(etcd_disk_wal_write_duration_seconds_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal write duration p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (irate(etcd_disk_wal_write_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd wal write duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(etcd_disk_wal_write_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(etcd_disk_wal_write_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(etcd_disk_wal_write_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_disk_wal_write_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd peer round trip time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_network_peer_round_trip_time_seconds_sum{}[$__rate_interval]) / rate(etcd_network_peer_round_trip_time_seconds_count{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd peer round trip time p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (instance, le) (irate(etcd_disk_wal_fsync_duration_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd peer round trip time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(irate(etcd_network_peer_round_trip_time_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(etcd_network_peer_round_trip_time_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(irate(etcd_network_peer_round_trip_time_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(irate(etcd_network_peer_round_trip_time_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd gRPC server started total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method) (rate(grpc_server_started_total{}[$__rate_interval])) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "etcd gRPC server handled total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (grpc_service, grpc_method, grpc_code) (rate(grpc_server_handled_total{}[$__rate_interval])) > 0",
     "legendFormat": "{{grpc_service}}/{{grpc_method}}: {{grpc_code}}"
    }
   ]
  },
  {
   "title": "etcd gRPC latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_server_handling_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd proposals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(etcd_server_proposals_pending)",
     "legendFormat": "pending"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_failed_total{}[$__rate_interval]))",
     "legendFormat": "failed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_committed_total{}[$__rate_interval]))",
     "legendFormat": "committed"
    },
    {
     "expr": "sum(rate(etcd_server_proposals_applied_total{}[$__rate_interval]))",
     "legendFormat": "applied"
    }
   ]
  },
  {
   "title": "etcd apply duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_server_apply_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_server_apply_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_server_apply_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_server_apply_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd leases granted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_lease_granted_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd lease ttl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_debugging_lease_ttl_total_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_debugging_lease_ttl_total_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_debugging_lease_ttl_total_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_lease_ttl_total_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd leases renewed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_lease_renewed_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd leases expired",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_server_lease_expired_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd leases revoked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_lease_revoked_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc revision",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_mvcc_current_revision[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc keys",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_debugging_mvcc_keys_total{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc ranges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_mvcc_range_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc put size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_debugging_mvcc_total_put_size_in_bytes[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc deletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_mvcc_delete_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc puts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_mvcc_put_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc ranges",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_mvcc_range_total{}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(etcd_mvcc_txn_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc db total size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_mvcc_db_total_size_in_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc db total size in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (etcd_mvcc_db_total_size_in_use_in_bytes{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd mvcc db fragmentation ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum by (instance) (etcd_mvcc_db_total_size_in_use_in_bytes / etcd_mvcc_db_total_size_in_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "etcd commit duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_disk_backend_commit_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd commit rebalance duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_disk_backend_commit_rebalance_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd commit write duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_disk_backend_commit_write_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "etcd commit spill duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "90%"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(etcd_debugging_disk_backend_commit_spill_duration_seconds_bucket{}[$__rate_interval])) by (le))",
     "legendFormat": "99%"
    }
   ]
  }
 ]
}