// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: api/proto/forgery.proto

package forgeryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForgeryControl_ForwardWebhook_FullMethodName        = "/persys.forgery.v1.ForgeryControl/ForwardWebhook"
	ForgeryControl_UpsertProject_FullMethodName         = "/persys.forgery.v1.ForgeryControl/UpsertProject"
	ForgeryControl_GetProject_FullMethodName            = "/persys.forgery.v1.ForgeryControl/GetProject"
	ForgeryControl_ListProjects_FullMethodName          = "/persys.forgery.v1.ForgeryControl/ListProjects"
	ForgeryControl_DeleteProject_FullMethodName         = "/persys.forgery.v1.ForgeryControl/DeleteProject"
	ForgeryControl_StoreGitHubCredential_FullMethodName = "/persys.forgery.v1.ForgeryControl/StoreGitHubCredential"
	ForgeryControl_ListUserRepositories_FullMethodName  = "/persys.forgery.v1.ForgeryControl/ListUserRepositories"
	ForgeryControl_RegisterWebhook_FullMethodName       = "/persys.forgery.v1.ForgeryControl/RegisterWebhook"
	ForgeryControl_TriggerBuild_FullMethodName          = "/persys.forgery.v1.ForgeryControl/TriggerBuild"
)

// ForgeryControlClient is the client API for ForgeryControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForgeryControlClient interface {
	ForwardWebhook(ctx context.Context, in *ForwardWebhookRequest, opts ...grpc.CallOption) (*ForwardWebhookResponse, error)
	UpsertProject(ctx context.Context, in *UpsertProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error)
	DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	StoreGitHubCredential(ctx context.Context, in *StoreGitHubCredentialRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	ListUserRepositories(ctx context.Context, in *ListUserRepositoriesRequest, opts ...grpc.CallOption) (*ListUserRepositoriesResponse, error)
	RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*OperationStatus, error)
	TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*OperationStatus, error)
}

type forgeryControlClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeryControlClient(cc grpc.ClientConnInterface) ForgeryControlClient {
	return &forgeryControlClient{cc}
}

func (c *forgeryControlClient) ForwardWebhook(ctx context.Context, in *ForwardWebhookRequest, opts ...grpc.CallOption) (*ForwardWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardWebhookResponse)
	err := c.cc.Invoke(ctx, ForgeryControl_ForwardWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) UpsertProject(ctx context.Context, in *UpsertProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ForgeryControl_UpsertProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) GetProject(ctx context.Context, in *GetProjectRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, ForgeryControl_GetProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) ListProjects(ctx context.Context, in *ListProjectsRequest, opts ...grpc.CallOption) (*ListProjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListProjectsResponse)
	err := c.cc.Invoke(ctx, ForgeryControl_ListProjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) DeleteProject(ctx context.Context, in *DeleteProjectRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, ForgeryControl_DeleteProject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) StoreGitHubCredential(ctx context.Context, in *StoreGitHubCredentialRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, ForgeryControl_StoreGitHubCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) ListUserRepositories(ctx context.Context, in *ListUserRepositoriesRequest, opts ...grpc.CallOption) (*ListUserRepositoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserRepositoriesResponse)
	err := c.cc.Invoke(ctx, ForgeryControl_ListUserRepositories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) RegisterWebhook(ctx context.Context, in *RegisterWebhookRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, ForgeryControl_RegisterWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeryControlClient) TriggerBuild(ctx context.Context, in *TriggerBuildRequest, opts ...grpc.CallOption) (*OperationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperationStatus)
	err := c.cc.Invoke(ctx, ForgeryControl_TriggerBuild_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgeryControlServer is the server API for ForgeryControl service.
// All implementations must embed UnimplementedForgeryControlServer
// for forward compatibility.
type ForgeryControlServer interface {
	ForwardWebhook(context.Context, *ForwardWebhookRequest) (*ForwardWebhookResponse, error)
	UpsertProject(context.Context, *UpsertProjectRequest) (*ProjectResponse, error)
	GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error)
	ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error)
	DeleteProject(context.Context, *DeleteProjectRequest) (*OperationStatus, error)
	StoreGitHubCredential(context.Context, *StoreGitHubCredentialRequest) (*OperationStatus, error)
	ListUserRepositories(context.Context, *ListUserRepositoriesRequest) (*ListUserRepositoriesResponse, error)
	RegisterWebhook(context.Context, *RegisterWebhookRequest) (*OperationStatus, error)
	TriggerBuild(context.Context, *TriggerBuildRequest) (*OperationStatus, error)
	mustEmbedUnimplementedForgeryControlServer()
}

// UnimplementedForgeryControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgeryControlServer struct{}

func (UnimplementedForgeryControlServer) ForwardWebhook(context.Context, *ForwardWebhookRequest) (*ForwardWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardWebhook not implemented")
}
func (UnimplementedForgeryControlServer) UpsertProject(context.Context, *UpsertProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertProject not implemented")
}
func (UnimplementedForgeryControlServer) GetProject(context.Context, *GetProjectRequest) (*ProjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProject not implemented")
}
func (UnimplementedForgeryControlServer) ListProjects(context.Context, *ListProjectsRequest) (*ListProjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProjects not implemented")
}
func (UnimplementedForgeryControlServer) DeleteProject(context.Context, *DeleteProjectRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteProject not implemented")
}
func (UnimplementedForgeryControlServer) StoreGitHubCredential(context.Context, *StoreGitHubCredentialRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreGitHubCredential not implemented")
}
func (UnimplementedForgeryControlServer) ListUserRepositories(context.Context, *ListUserRepositoriesRequest) (*ListUserRepositoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserRepositories not implemented")
}
func (UnimplementedForgeryControlServer) RegisterWebhook(context.Context, *RegisterWebhookRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWebhook not implemented")
}
func (UnimplementedForgeryControlServer) TriggerBuild(context.Context, *TriggerBuildRequest) (*OperationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerBuild not implemented")
}
func (UnimplementedForgeryControlServer) mustEmbedUnimplementedForgeryControlServer() {}
func (UnimplementedForgeryControlServer) testEmbeddedByValue()                        {}

// UnsafeForgeryControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgeryControlServer will
// result in compilation errors.
type UnsafeForgeryControlServer interface {
	mustEmbedUnimplementedForgeryControlServer()
}

func RegisterForgeryControlServer(s grpc.ServiceRegistrar, srv ForgeryControlServer) {
	// If the following call panics, it indicates UnimplementedForgeryControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForgeryControl_ServiceDesc, srv)
}

func _ForgeryControl_ForwardWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).ForwardWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_ForwardWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).ForwardWebhook(ctx, req.(*ForwardWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_UpsertProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).UpsertProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_UpsertProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).UpsertProject(ctx, req.(*UpsertProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_GetProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).GetProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_GetProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).GetProject(ctx, req.(*GetProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_ListProjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).ListProjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_ListProjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).ListProjects(ctx, req.(*ListProjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_DeleteProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).DeleteProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_DeleteProject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).DeleteProject(ctx, req.(*DeleteProjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_StoreGitHubCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreGitHubCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).StoreGitHubCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_StoreGitHubCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).StoreGitHubCredential(ctx, req.(*StoreGitHubCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_ListUserRepositories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRepositoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).ListUserRepositories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_ListUserRepositories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).ListUserRepositories(ctx, req.(*ListUserRepositoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_RegisterWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).RegisterWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_RegisterWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).RegisterWebhook(ctx, req.(*RegisterWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeryControl_TriggerBuild_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerBuildRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeryControlServer).TriggerBuild(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeryControl_TriggerBuild_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeryControlServer).TriggerBuild(ctx, req.(*TriggerBuildRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForgeryControl_ServiceDesc is the grpc.ServiceDesc for ForgeryControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForgeryControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "persys.forgery.v1.ForgeryControl",
	HandlerType: (*ForgeryControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardWebhook",
			Handler:    _ForgeryControl_ForwardWebhook_Handler,
		},
		{
			MethodName: "UpsertProject",
			Handler:    _ForgeryControl_UpsertProject_Handler,
		},
		{
			MethodName: "GetProject",
			Handler:    _ForgeryControl_GetProject_Handler,
		},
		{
			MethodName: "ListProjects",
			Handler:    _ForgeryControl_ListProjects_Handler,
		},
		{
			MethodName: "DeleteProject",
			Handler:    _ForgeryControl_DeleteProject_Handler,
		},
		{
			MethodName: "StoreGitHubCredential",
			Handler:    _ForgeryControl_StoreGitHubCredential_Handler,
		},
		{
			MethodName: "ListUserRepositories",
			Handler:    _ForgeryControl_ListUserRepositories_Handler,
		},
		{
			MethodName: "RegisterWebhook",
			Handler:    _ForgeryControl_RegisterWebhook_Handler,
		},
		{
			MethodName: "TriggerBuild",
			Handler:    _ForgeryControl_TriggerBuild_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/forgery.proto",
}
