# Persys Cloud Monitoring Stack

services:
  # --- Prometheus (Metrics collection) ---
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - persys-cloud-net

  # --- Grafana (Metrics visualization) ---
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP:-false}
    ports:
      - "3000:3000"
    networks:
      - persys-cloud-net
    depends_on:
      - prometheus

  # --- Pyroscope (Profiling) ---
  pyroscope:
    image: grafana/pyroscope:latest
    ports:
      - "4040:4040"
    command: ["server"]
    networks:
      - persys-cloud-net
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pyroscope_data:/data

  # --- Alloy (Profile Scraping) ---
  alloy:
    image: grafana/alloy:latest
    volumes:
      - ./alloy/alloy-config.alloy:/etc/alloy/config.alloy
      - /etc/localtime:/etc/localtime:ro
    command: ["run", "/etc/alloy/config.alloy"]
    networks:
      - persys-cloud-net
    depends_on:
      - pyroscope

  # --- Jaeger (Distributed tracing) ---
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=${COLLECTOR_OTLP_ENABLED:-true}
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - persys-cloud-net

  # --- Node Exporter (Host metrics for Prometheus) ---
  node_exporter:
    container_name: node_exporter_container
    restart: always
    image: prom/node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - persys-cloud-net

# --- Volumes for persistent data ---
volumes:
  pyroscope_data:
  prometheus_data:
  grafana_data:

# --- Shared overlay network for all services ---
networks:
  persys-cloud-net:
    driver: bridge
