// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: cloud-mgmt.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CloudMgmtServiceClient is the client API for CloudMgmtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CloudMgmtServiceClient interface {
	Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error)
}

type cloudMgmtServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCloudMgmtServiceClient(cc grpc.ClientConnInterface) CloudMgmtServiceClient {
	return &cloudMgmtServiceClient{cc}
}

func (c *cloudMgmtServiceClient) Services(ctx context.Context, in *ServicesRequest, opts ...grpc.CallOption) (*ServicesResponse, error) {
	out := new(ServicesResponse)
	err := c.cc.Invoke(ctx, "/cloudMgmt.CloudMgmtService/services", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CloudMgmtServiceServer is the server API for CloudMgmtService service.
// All implementations must embed UnimplementedCloudMgmtServiceServer
// for forward compatibility
type CloudMgmtServiceServer interface {
	Services(context.Context, *ServicesRequest) (*ServicesResponse, error)
	mustEmbedUnimplementedCloudMgmtServiceServer()
}

// UnimplementedCloudMgmtServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCloudMgmtServiceServer struct {
}

func (UnimplementedCloudMgmtServiceServer) Services(context.Context, *ServicesRequest) (*ServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Services not implemented")
}
func (UnimplementedCloudMgmtServiceServer) mustEmbedUnimplementedCloudMgmtServiceServer() {}

// UnsafeCloudMgmtServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CloudMgmtServiceServer will
// result in compilation errors.
type UnsafeCloudMgmtServiceServer interface {
	mustEmbedUnimplementedCloudMgmtServiceServer()
}

func RegisterCloudMgmtServiceServer(s grpc.ServiceRegistrar, srv CloudMgmtServiceServer) {
	s.RegisterService(&CloudMgmtService_ServiceDesc, srv)
}

func _CloudMgmtService_Services_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CloudMgmtServiceServer).Services(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cloudMgmt.CloudMgmtService/services",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CloudMgmtServiceServer).Services(ctx, req.(*ServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CloudMgmtService_ServiceDesc is the grpc.ServiceDesc for CloudMgmtService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CloudMgmtService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cloudMgmt.CloudMgmtService",
	HandlerType: (*CloudMgmtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "services",
			Handler:    _CloudMgmtService_Services_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud-mgmt.proto",
}
