syntax = "proto3";

package vaultmanager;

option go_package = "github.com/persys-dev/persys-cloud/pkg/vaultmanager";

service VaultManagerService {
  rpc GetServiceCredentials(GetServiceCredentialsRequest) returns (ServiceCredentialsResponse);
  rpc RotateServiceSecretID(RotateServiceSecretIDRequest) returns (ServiceCredentialsResponse);
}

message GetServiceCredentialsRequest {
  string service_name = 1;
}

message RotateServiceSecretIDRequest {
  string service_name = 1;
}

message ServiceCredentialsResponse {
  string role_id = 1;
  string secret_id = 2;
  int64 expires_at = 3; // Unix timestamp seconds
  string message = 4;
}