apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: pyroscope
    type: pyroscope
    access: proxy
    url: http://pyroscope:4040
    isDefault: true
    editable: true