// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: automation.proto

package automationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PolicyType int32

const (
	PolicyType_POLICY_TYPE_UNSPECIFIED PolicyType = 0
	PolicyType_POLICY_TYPE_SCALE       PolicyType = 1
	PolicyType_POLICY_TYPE_SCHEDULE    PolicyType = 2
	PolicyType_POLICY_TYPE_OFFLOAD     PolicyType = 3
	PolicyType_POLICY_TYPE_DRIFT       PolicyType = 4
	PolicyType_POLICY_TYPE_REDEPLOY    PolicyType = 5
)

// Enum value maps for PolicyType.
var (
	PolicyType_name = map[int32]string{
		0: "POLICY_TYPE_UNSPECIFIED",
		1: "POLICY_TYPE_SCALE",
		2: "POLICY_TYPE_SCHEDULE",
		3: "POLICY_TYPE_OFFLOAD",
		4: "POLICY_TYPE_DRIFT",
		5: "POLICY_TYPE_REDEPLOY",
	}
	PolicyType_value = map[string]int32{
		"POLICY_TYPE_UNSPECIFIED": 0,
		"POLICY_TYPE_SCALE":       1,
		"POLICY_TYPE_SCHEDULE":    2,
		"POLICY_TYPE_OFFLOAD":     3,
		"POLICY_TYPE_DRIFT":       4,
		"POLICY_TYPE_REDEPLOY":    5,
	}
)

func (x PolicyType) Enum() *PolicyType {
	p := new(PolicyType)
	*p = x
	return p
}

func (x PolicyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PolicyType) Descriptor() protoreflect.EnumDescriptor {
	return file_automation_proto_enumTypes[0].Descriptor()
}

func (PolicyType) Type() protoreflect.EnumType {
	return &file_automation_proto_enumTypes[0]
}

func (x PolicyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PolicyType.Descriptor instead.
func (PolicyType) EnumDescriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{0}
}

type Policy struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TargetWorkload      string                 `protobuf:"bytes,3,opt,name=target_workload,json=targetWorkload,proto3" json:"target_workload,omitempty"`
	Type                PolicyType             `protobuf:"varint,4,opt,name=type,proto3,enum=persys.automation.v1.PolicyType" json:"type,omitempty"`
	ConditionExpression string                 `protobuf:"bytes,5,opt,name=condition_expression,json=conditionExpression,proto3" json:"condition_expression,omitempty"`
	ActionExpression    string                 `protobuf:"bytes,6,opt,name=action_expression,json=actionExpression,proto3" json:"action_expression,omitempty"`
	Enabled             bool                   `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{0}
}

func (x *Policy) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetTargetWorkload() string {
	if x != nil {
		return x.TargetWorkload
	}
	return ""
}

func (x *Policy) GetType() PolicyType {
	if x != nil {
		return x.Type
	}
	return PolicyType_POLICY_TYPE_UNSPECIFIED
}

func (x *Policy) GetConditionExpression() string {
	if x != nil {
		return x.ConditionExpression
	}
	return ""
}

func (x *Policy) GetActionExpression() string {
	if x != nil {
		return x.ActionExpression
	}
	return ""
}

func (x *Policy) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Policy) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Policy) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreatePolicyRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TargetWorkload      string                 `protobuf:"bytes,2,opt,name=target_workload,json=targetWorkload,proto3" json:"target_workload,omitempty"`
	Type                PolicyType             `protobuf:"varint,3,opt,name=type,proto3,enum=persys.automation.v1.PolicyType" json:"type,omitempty"`
	ConditionExpression string                 `protobuf:"bytes,4,opt,name=condition_expression,json=conditionExpression,proto3" json:"condition_expression,omitempty"`
	ActionExpression    string                 `protobuf:"bytes,5,opt,name=action_expression,json=actionExpression,proto3" json:"action_expression,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreatePolicyRequest) Reset() {
	*x = CreatePolicyRequest{}
	mi := &file_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyRequest) ProtoMessage() {}

func (x *CreatePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyRequest.ProtoReflect.Descriptor instead.
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePolicyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreatePolicyRequest) GetTargetWorkload() string {
	if x != nil {
		return x.TargetWorkload
	}
	return ""
}

func (x *CreatePolicyRequest) GetType() PolicyType {
	if x != nil {
		return x.Type
	}
	return PolicyType_POLICY_TYPE_UNSPECIFIED
}

func (x *CreatePolicyRequest) GetConditionExpression() string {
	if x != nil {
		return x.ConditionExpression
	}
	return ""
}

func (x *CreatePolicyRequest) GetActionExpression() string {
	if x != nil {
		return x.ActionExpression
	}
	return ""
}

type CreatePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePolicyResponse) Reset() {
	*x = CreatePolicyResponse{}
	mi := &file_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePolicyResponse) ProtoMessage() {}

func (x *CreatePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePolicyResponse.ProtoReflect.Descriptor instead.
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type ListPoliciesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IncludeDisabled bool                   `protobuf:"varint,1,opt,name=include_disabled,json=includeDisabled,proto3" json:"include_disabled,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{3}
}

func (x *ListPoliciesRequest) GetIncludeDisabled() bool {
	if x != nil {
		return x.IncludeDisabled
	}
	return false
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{4}
}

func (x *ListPoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type EnablePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePolicyRequest) Reset() {
	*x = EnablePolicyRequest{}
	mi := &file_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePolicyRequest) ProtoMessage() {}

func (x *EnablePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePolicyRequest.ProtoReflect.Descriptor instead.
func (*EnablePolicyRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{5}
}

func (x *EnablePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type EnablePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePolicyResponse) Reset() {
	*x = EnablePolicyResponse{}
	mi := &file_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePolicyResponse) ProtoMessage() {}

func (x *EnablePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnablePolicyResponse.ProtoReflect.Descriptor instead.
func (*EnablePolicyResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{6}
}

func (x *EnablePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type DisablePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePolicyRequest) Reset() {
	*x = DisablePolicyRequest{}
	mi := &file_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePolicyRequest) ProtoMessage() {}

func (x *DisablePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePolicyRequest.ProtoReflect.Descriptor instead.
func (*DisablePolicyRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{7}
}

func (x *DisablePolicyRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type DisablePolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        *Policy                `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePolicyResponse) Reset() {
	*x = DisablePolicyResponse{}
	mi := &file_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePolicyResponse) ProtoMessage() {}

func (x *DisablePolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePolicyResponse.ProtoReflect.Descriptor instead.
func (*DisablePolicyResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{8}
}

func (x *DisablePolicyResponse) GetPolicy() *Policy {
	if x != nil {
		return x.Policy
	}
	return nil
}

type EvaluateNowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateNowRequest) Reset() {
	*x = EvaluateNowRequest{}
	mi := &file_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateNowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateNowRequest) ProtoMessage() {}

func (x *EvaluateNowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateNowRequest.ProtoReflect.Descriptor instead.
func (*EvaluateNowRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{9}
}

func (x *EvaluateNowRequest) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

type PolicyEvaluationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Matched       bool                   `protobuf:"varint,2,opt,name=matched,proto3" json:"matched,omitempty"`
	Dispatched    bool                   `protobuf:"varint,3,opt,name=dispatched,proto3" json:"dispatched,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEvaluationResult) Reset() {
	*x = PolicyEvaluationResult{}
	mi := &file_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEvaluationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEvaluationResult) ProtoMessage() {}

func (x *PolicyEvaluationResult) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEvaluationResult.ProtoReflect.Descriptor instead.
func (*PolicyEvaluationResult) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyEvaluationResult) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyEvaluationResult) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *PolicyEvaluationResult) GetDispatched() bool {
	if x != nil {
		return x.Dispatched
	}
	return false
}

func (x *PolicyEvaluationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluateNowResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Results       []*PolicyEvaluationResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateNowResponse) Reset() {
	*x = EvaluateNowResponse{}
	mi := &file_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateNowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateNowResponse) ProtoMessage() {}

func (x *EvaluateNowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateNowResponse.ProtoReflect.Descriptor instead.
func (*EvaluateNowResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluateNowResponse) GetResults() []*PolicyEvaluationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListAuditLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogRequest) Reset() {
	*x = ListAuditLogRequest{}
	mi := &file_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogRequest) ProtoMessage() {}

func (x *ListAuditLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogRequest.ProtoReflect.Descriptor instead.
func (*ListAuditLogRequest) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{12}
}

func (x *ListAuditLogRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type AuditEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PolicyId       string                 `protobuf:"bytes,2,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyName     string                 `protobuf:"bytes,3,opt,name=policy_name,json=policyName,proto3" json:"policy_name,omitempty"`
	TargetWorkload string                 `protobuf:"bytes,4,opt,name=target_workload,json=targetWorkload,proto3" json:"target_workload,omitempty"`
	Matched        bool                   `protobuf:"varint,5,opt,name=matched,proto3" json:"matched,omitempty"`
	Dispatched     bool                   `protobuf:"varint,6,opt,name=dispatched,proto3" json:"dispatched,omitempty"`
	Reason         string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	OldState       string                 `protobuf:"bytes,8,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState       string                 `protobuf:"bytes,9,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_automation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{13}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *AuditEntry) GetPolicyName() string {
	if x != nil {
		return x.PolicyName
	}
	return ""
}

func (x *AuditEntry) GetTargetWorkload() string {
	if x != nil {
		return x.TargetWorkload
	}
	return ""
}

func (x *AuditEntry) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *AuditEntry) GetDispatched() bool {
	if x != nil {
		return x.Dispatched
	}
	return false
}

func (x *AuditEntry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AuditEntry) GetOldState() string {
	if x != nil {
		return x.OldState
	}
	return ""
}

func (x *AuditEntry) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *AuditEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ListAuditLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAuditLogResponse) Reset() {
	*x = ListAuditLogResponse{}
	mi := &file_automation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAuditLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAuditLogResponse) ProtoMessage() {}

func (x *ListAuditLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_automation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAuditLogResponse.ProtoReflect.Descriptor instead.
func (*ListAuditLogResponse) Descriptor() ([]byte, []int) {
	return file_automation_proto_rawDescGZIP(), []int{14}
}

func (x *ListAuditLogResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_automation_proto protoreflect.FileDescriptor

const file_automation_proto_rawDesc = "" +
	"\n" +
	"\x10automation.proto\x12\x14persys.automation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\x06Policy\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0ftarget_workload\x18\x03 \x01(\tR\x0etargetWorkload\x124\n" +
	"\x04type\x18\x04 \x01(\x0e2 .persys.automation.v1.PolicyTypeR\x04type\x121\n" +
	"\x14condition_expression\x18\x05 \x01(\tR\x13conditionExpression\x12+\n" +
	"\x11action_expression\x18\x06 \x01(\tR\x10actionExpression\x12\x18\n" +
	"\aenabled\x18\a \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe8\x01\n" +
	"\x13CreatePolicyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12'\n" +
	"\x0ftarget_workload\x18\x02 \x01(\tR\x0etargetWorkload\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .persys.automation.v1.PolicyTypeR\x04type\x121\n" +
	"\x14condition_expression\x18\x04 \x01(\tR\x13conditionExpression\x12+\n" +
	"\x11action_expression\x18\x05 \x01(\tR\x10actionExpression\"L\n" +
	"\x14CreatePolicyResponse\x124\n" +
	"\x06policy\x18\x01 \x01(\v2\x1c.persys.automation.v1.PolicyR\x06policy\"@\n" +
	"\x13ListPoliciesRequest\x12)\n" +
	"\x10include_disabled\x18\x01 \x01(\bR\x0fincludeDisabled\"P\n" +
	"\x14ListPoliciesResponse\x128\n" +
	"\bpolicies\x18\x01 \x03(\v2\x1c.persys.automation.v1.PolicyR\bpolicies\"2\n" +
	"\x13EnablePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"L\n" +
	"\x14EnablePolicyResponse\x124\n" +
	"\x06policy\x18\x01 \x01(\v2\x1c.persys.automation.v1.PolicyR\x06policy\"3\n" +
	"\x14DisablePolicyRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"M\n" +
	"\x15DisablePolicyResponse\x124\n" +
	"\x06policy\x18\x01 \x01(\v2\x1c.persys.automation.v1.PolicyR\x06policy\"1\n" +
	"\x12EvaluateNowRequest\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\"\x87\x01\n" +
	"\x16PolicyEvaluationResult\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x18\n" +
	"\amatched\x18\x02 \x01(\bR\amatched\x12\x1e\n" +
	"\n" +
	"dispatched\x18\x03 \x01(\bR\n" +
	"dispatched\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"]\n" +
	"\x13EvaluateNowResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.persys.automation.v1.PolicyEvaluationResultR\aresults\"+\n" +
	"\x13ListAuditLogRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"\xc9\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tpolicy_id\x18\x02 \x01(\tR\bpolicyId\x12\x1f\n" +
	"\vpolicy_name\x18\x03 \x01(\tR\n" +
	"policyName\x12'\n" +
	"\x0ftarget_workload\x18\x04 \x01(\tR\x0etargetWorkload\x12\x18\n" +
	"\amatched\x18\x05 \x01(\bR\amatched\x12\x1e\n" +
	"\n" +
	"dispatched\x18\x06 \x01(\bR\n" +
	"dispatched\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x12\x1b\n" +
	"\told_state\x18\b \x01(\tR\boldState\x12\x1b\n" +
	"\tnew_state\x18\t \x01(\tR\bnewState\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"R\n" +
	"\x14ListAuditLogResponse\x12:\n" +
	"\aentries\x18\x01 \x03(\v2 .persys.automation.v1.AuditEntryR\aentries*\xa4\x01\n" +
	"\n" +
	"PolicyType\x12\x1b\n" +
	"\x17POLICY_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11POLICY_TYPE_SCALE\x10\x01\x12\x18\n" +
	"\x14POLICY_TYPE_SCHEDULE\x10\x02\x12\x17\n" +
	"\x13POLICY_TYPE_OFFLOAD\x10\x03\x12\x15\n" +
	"\x11POLICY_TYPE_DRIFT\x10\x04\x12\x18\n" +
	"\x14POLICY_TYPE_REDEPLOY\x10\x052\xfd\x04\n" +
	"\x11AutomationControl\x12e\n" +
	"\fCreatePolicy\x12).persys.automation.v1.CreatePolicyRequest\x1a*.persys.automation.v1.CreatePolicyResponse\x12e\n" +
	"\fListPolicies\x12).persys.automation.v1.ListPoliciesRequest\x1a*.persys.automation.v1.ListPoliciesResponse\x12e\n" +
	"\fEnablePolicy\x12).persys.automation.v1.EnablePolicyRequest\x1a*.persys.automation.v1.EnablePolicyResponse\x12h\n" +
	"\rDisablePolicy\x12*.persys.automation.v1.DisablePolicyRequest\x1a+.persys.automation.v1.DisablePolicyResponse\x12b\n" +
	"\vEvaluateNow\x12(.persys.automation.v1.EvaluateNowRequest\x1a).persys.automation.v1.EvaluateNowResponse\x12e\n" +
	"\fListAuditLog\x12).persys.automation.v1.ListAuditLogRequest\x1a*.persys.automation.v1.ListAuditLogResponseBMZKgithub.com/persys-dev/persys-cloud/persys-automation/api/proto;automationv1b\x06proto3"

var (
	file_automation_proto_rawDescOnce sync.Once
	file_automation_proto_rawDescData []byte
)

func file_automation_proto_rawDescGZIP() []byte {
	file_automation_proto_rawDescOnce.Do(func() {
		file_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_automation_proto_rawDesc), len(file_automation_proto_rawDesc)))
	})
	return file_automation_proto_rawDescData
}

var file_automation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_automation_proto_goTypes = []any{
	(PolicyType)(0),                // 0: persys.automation.v1.PolicyType
	(*Policy)(nil),                 // 1: persys.automation.v1.Policy
	(*CreatePolicyRequest)(nil),    // 2: persys.automation.v1.CreatePolicyRequest
	(*CreatePolicyResponse)(nil),   // 3: persys.automation.v1.CreatePolicyResponse
	(*ListPoliciesRequest)(nil),    // 4: persys.automation.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),   // 5: persys.automation.v1.ListPoliciesResponse
	(*EnablePolicyRequest)(nil),    // 6: persys.automation.v1.EnablePolicyRequest
	(*EnablePolicyResponse)(nil),   // 7: persys.automation.v1.EnablePolicyResponse
	(*DisablePolicyRequest)(nil),   // 8: persys.automation.v1.DisablePolicyRequest
	(*DisablePolicyResponse)(nil),  // 9: persys.automation.v1.DisablePolicyResponse
	(*EvaluateNowRequest)(nil),     // 10: persys.automation.v1.EvaluateNowRequest
	(*PolicyEvaluationResult)(nil), // 11: persys.automation.v1.PolicyEvaluationResult
	(*EvaluateNowResponse)(nil),    // 12: persys.automation.v1.EvaluateNowResponse
	(*ListAuditLogRequest)(nil),    // 13: persys.automation.v1.ListAuditLogRequest
	(*AuditEntry)(nil),             // 14: persys.automation.v1.AuditEntry
	(*ListAuditLogResponse)(nil),   // 15: persys.automation.v1.ListAuditLogResponse
	(*timestamppb.Timestamp)(nil),  // 16: google.protobuf.Timestamp
}
var file_automation_proto_depIdxs = []int32{
	0,  // 0: persys.automation.v1.Policy.type:type_name -> persys.automation.v1.PolicyType
	16, // 1: persys.automation.v1.Policy.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: persys.automation.v1.Policy.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: persys.automation.v1.CreatePolicyRequest.type:type_name -> persys.automation.v1.PolicyType
	1,  // 4: persys.automation.v1.CreatePolicyResponse.policy:type_name -> persys.automation.v1.Policy
	1,  // 5: persys.automation.v1.ListPoliciesResponse.policies:type_name -> persys.automation.v1.Policy
	1,  // 6: persys.automation.v1.EnablePolicyResponse.policy:type_name -> persys.automation.v1.Policy
	1,  // 7: persys.automation.v1.DisablePolicyResponse.policy:type_name -> persys.automation.v1.Policy
	11, // 8: persys.automation.v1.EvaluateNowResponse.results:type_name -> persys.automation.v1.PolicyEvaluationResult
	16, // 9: persys.automation.v1.AuditEntry.timestamp:type_name -> google.protobuf.Timestamp
	14, // 10: persys.automation.v1.ListAuditLogResponse.entries:type_name -> persys.automation.v1.AuditEntry
	2,  // 11: persys.automation.v1.AutomationControl.CreatePolicy:input_type -> persys.automation.v1.CreatePolicyRequest
	4,  // 12: persys.automation.v1.AutomationControl.ListPolicies:input_type -> persys.automation.v1.ListPoliciesRequest
	6,  // 13: persys.automation.v1.AutomationControl.EnablePolicy:input_type -> persys.automation.v1.EnablePolicyRequest
	8,  // 14: persys.automation.v1.AutomationControl.DisablePolicy:input_type -> persys.automation.v1.DisablePolicyRequest
	10, // 15: persys.automation.v1.AutomationControl.EvaluateNow:input_type -> persys.automation.v1.EvaluateNowRequest
	13, // 16: persys.automation.v1.AutomationControl.ListAuditLog:input_type -> persys.automation.v1.ListAuditLogRequest
	3,  // 17: persys.automation.v1.AutomationControl.CreatePolicy:output_type -> persys.automation.v1.CreatePolicyResponse
	5,  // 18: persys.automation.v1.AutomationControl.ListPolicies:output_type -> persys.automation.v1.ListPoliciesResponse
	7,  // 19: persys.automation.v1.AutomationControl.EnablePolicy:output_type -> persys.automation.v1.EnablePolicyResponse
	9,  // 20: persys.automation.v1.AutomationControl.DisablePolicy:output_type -> persys.automation.v1.DisablePolicyResponse
	12, // 21: persys.automation.v1.AutomationControl.EvaluateNow:output_type -> persys.automation.v1.EvaluateNowResponse
	15, // 22: persys.automation.v1.AutomationControl.ListAuditLog:output_type -> persys.automation.v1.ListAuditLogResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_automation_proto_init() }
func file_automation_proto_init() {
	if File_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_automation_proto_rawDesc), len(file_automation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_automation_proto_goTypes,
		DependencyIndexes: file_automation_proto_depIdxs,
		EnumInfos:         file_automation_proto_enumTypes,
		MessageInfos:      file_automation_proto_msgTypes,
	}.Build()
	File_automation_proto = out.File
	file_automation_proto_goTypes = nil
	file_automation_proto_depIdxs = nil
}
