apiVersion: v1
kind: Service
metadata:
  namespace: persys
  name: api-gateway-global
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: persys-dev
spec:
  type: LoadBalancer
  ports:
    -
      port: 80
      targetPort: 8551
  selector:
    app: api-gateway