apiVersion: v1
kind: Service
metadata:
    namespace: persys
    name: api-gateway-global
    annotations:
        service.beta.kubernetes.io/azure-dns-label-name: persys
spec:
    type: LoadBalancer
    ports:
        -
            port: 80
            targetPort: 8551
    selector:
        app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
    namespace: persys
    name: events-manager
spec:
    selector:
        app: events-manager
    ports:
        - protocol: TCP
          port: 8662
          targetPort: 8662
---
apiVersion: v1
kind: Service
metadata:
    namespace: persys
    name: ci-service
spec:
    selector:
        app: ci-service
    ports:
        - protocol: TCP
          port: 8551
          targetPort: 8551