// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadType int32

const (
	WorkloadType_WORKLOAD_TYPE_UNSPECIFIED WorkloadType = 0
	WorkloadType_WORKLOAD_TYPE_CONTAINER   WorkloadType = 1
	WorkloadType_WORKLOAD_TYPE_COMPOSE     WorkloadType = 2
	WorkloadType_WORKLOAD_TYPE_VM          WorkloadType = 3
)

// Enum value maps for WorkloadType.
var (
	WorkloadType_name = map[int32]string{
		0: "WORKLOAD_TYPE_UNSPECIFIED",
		1: "WORKLOAD_TYPE_CONTAINER",
		2: "WORKLOAD_TYPE_COMPOSE",
		3: "WORKLOAD_TYPE_VM",
	}
	WorkloadType_value = map[string]int32{
		"WORKLOAD_TYPE_UNSPECIFIED": 0,
		"WORKLOAD_TYPE_CONTAINER":   1,
		"WORKLOAD_TYPE_COMPOSE":     2,
		"WORKLOAD_TYPE_VM":          3,
	}
)

func (x WorkloadType) Enum() *WorkloadType {
	p := new(WorkloadType)
	*p = x
	return p
}

func (x WorkloadType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (WorkloadType) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x WorkloadType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadType.Descriptor instead.
func (WorkloadType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type DesiredState int32

const (
	DesiredState_DESIRED_STATE_UNSPECIFIED DesiredState = 0
	DesiredState_DESIRED_STATE_RUNNING     DesiredState = 1
	DesiredState_DESIRED_STATE_STOPPED     DesiredState = 2
)

// Enum value maps for DesiredState.
var (
	DesiredState_name = map[int32]string{
		0: "DESIRED_STATE_UNSPECIFIED",
		1: "DESIRED_STATE_RUNNING",
		2: "DESIRED_STATE_STOPPED",
	}
	DesiredState_value = map[string]int32{
		"DESIRED_STATE_UNSPECIFIED": 0,
		"DESIRED_STATE_RUNNING":     1,
		"DESIRED_STATE_STOPPED":     2,
	}
)

func (x DesiredState) Enum() *DesiredState {
	p := new(DesiredState)
	*p = x
	return p
}

func (x DesiredState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesiredState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (DesiredState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x DesiredState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesiredState.Descriptor instead.
func (DesiredState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

type ActualState int32

const (
	ActualState_ACTUAL_STATE_UNSPECIFIED ActualState = 0
	ActualState_ACTUAL_STATE_PENDING     ActualState = 1
	ActualState_ACTUAL_STATE_RUNNING     ActualState = 2
	ActualState_ACTUAL_STATE_STOPPED     ActualState = 3
	ActualState_ACTUAL_STATE_FAILED      ActualState = 4
	ActualState_ACTUAL_STATE_UNKNOWN     ActualState = 5
)

// Enum value maps for ActualState.
var (
	ActualState_name = map[int32]string{
		0: "ACTUAL_STATE_UNSPECIFIED",
		1: "ACTUAL_STATE_PENDING",
		2: "ACTUAL_STATE_RUNNING",
		3: "ACTUAL_STATE_STOPPED",
		4: "ACTUAL_STATE_FAILED",
		5: "ACTUAL_STATE_UNKNOWN",
	}
	ActualState_value = map[string]int32{
		"ACTUAL_STATE_UNSPECIFIED": 0,
		"ACTUAL_STATE_PENDING":     1,
		"ACTUAL_STATE_RUNNING":     2,
		"ACTUAL_STATE_STOPPED":     3,
		"ACTUAL_STATE_FAILED":      4,
		"ACTUAL_STATE_UNKNOWN":     5,
	}
)

func (x ActualState) Enum() *ActualState {
	p := new(ActualState)
	*p = x
	return p
}

func (x ActualState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActualState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (ActualState) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x ActualState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActualState.Descriptor instead.
func (ActualState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

type ApplyWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          WorkloadType           `protobuf:"varint,2,opt,name=type,proto3,enum=persys.agent.v1.WorkloadType" json:"type,omitempty"`
	RevisionId    string                 `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	DesiredState  DesiredState           `protobuf:"varint,4,opt,name=desired_state,json=desiredState,proto3,enum=persys.agent.v1.DesiredState" json:"desired_state,omitempty"`
	Spec          *WorkloadSpec          `protobuf:"bytes,5,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWorkloadRequest) Reset() {
	*x = ApplyWorkloadRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWorkloadRequest) ProtoMessage() {}

func (x *ApplyWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWorkloadRequest.ProtoReflect.Descriptor instead.
func (*ApplyWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ApplyWorkloadRequest) GetType() WorkloadType {
	if x != nil {
		return x.Type
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

func (x *ApplyWorkloadRequest) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *ApplyWorkloadRequest) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *ApplyWorkloadRequest) GetSpec() *WorkloadSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type ApplyWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applied       bool                   `protobuf:"varint,1,opt,name=applied,proto3" json:"applied,omitempty"`
	Skipped       bool                   `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"` // true if revision already applied
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Status        *WorkloadStatus        `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyWorkloadResponse) Reset() {
	*x = ApplyWorkloadResponse{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyWorkloadResponse) ProtoMessage() {}

func (x *ApplyWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyWorkloadResponse.ProtoReflect.Descriptor instead.
func (*ApplyWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ApplyWorkloadResponse) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *ApplyWorkloadResponse) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

func (x *ApplyWorkloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApplyWorkloadResponse) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteWorkloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadRequest) Reset() {
	*x = DeleteWorkloadRequest{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadRequest) ProtoMessage() {}

func (x *DeleteWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadRequest.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteWorkloadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWorkloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWorkloadResponse) Reset() {
	*x = DeleteWorkloadResponse{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWorkloadResponse) ProtoMessage() {}

func (x *DeleteWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWorkloadResponse.ProtoReflect.Descriptor instead.
func (*DeleteWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteWorkloadResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteWorkloadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetWorkloadStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatusRequest) Reset() {
	*x = GetWorkloadStatusRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusRequest) ProtoMessage() {}

func (x *GetWorkloadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusRequest.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkloadStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetWorkloadStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *WorkloadStatus        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkloadStatusResponse) Reset() {
	*x = GetWorkloadStatusResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkloadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkloadStatusResponse) ProtoMessage() {}

func (x *GetWorkloadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkloadStatusResponse.ProtoReflect.Descriptor instead.
func (*GetWorkloadStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkloadStatusResponse) GetStatus() *WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ListWorkloadsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          WorkloadType           `protobuf:"varint,1,opt,name=type,proto3,enum=persys.agent.v1.WorkloadType" json:"type,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsRequest) Reset() {
	*x = ListWorkloadsRequest{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsRequest) ProtoMessage() {}

func (x *ListWorkloadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkloadsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ListWorkloadsRequest) GetType() WorkloadType {
	if x != nil {
		return x.Type
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

type ListWorkloadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*WorkloadStatus      `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkloadsResponse) Reset() {
	*x = ListWorkloadsResponse{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkloadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkloadsResponse) ProtoMessage() {}

func (x *ListWorkloadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkloadsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkloadsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListWorkloadsResponse) GetWorkloads() []*WorkloadStatus {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

type HealthCheckResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Healthy           bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version           string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	RuntimeStatus     map[string]string      `protobuf:"bytes,3,rep,name=runtime_status,json=runtimeStatus,proto3" json:"runtime_status,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MemoryUtilization float64                `protobuf:"fixed64,4,opt,name=memory_utilization,json=memoryUtilization,proto3" json:"memory_utilization,omitempty"` // Memory utilization percentage (0-100)
	CpuUtilization    float64                `protobuf:"fixed64,5,opt,name=cpu_utilization,json=cpuUtilization,proto3" json:"cpu_utilization,omitempty"`          // CPU utilization percentage (0-100)
	DiskUtilization   float64                `protobuf:"fixed64,6,opt,name=disk_utilization,json=diskUtilization,proto3" json:"disk_utilization,omitempty"`       // Disk utilization percentage for root mount (0-100)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetRuntimeStatus() map[string]string {
	if x != nil {
		return x.RuntimeStatus
	}
	return nil
}

func (x *HealthCheckResponse) GetMemoryUtilization() float64 {
	if x != nil {
		return x.MemoryUtilization
	}
	return 0
}

func (x *HealthCheckResponse) GetCpuUtilization() float64 {
	if x != nil {
		return x.CpuUtilization
	}
	return 0
}

func (x *HealthCheckResponse) GetDiskUtilization() float64 {
	if x != nil {
		return x.DiskUtilization
	}
	return 0
}

type ListActionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadId    string                 `protobuf:"bytes,1,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`     // optional filter
	ActionType    string                 `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`     // optional filter: apply_workload, delete_workload, ...
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                               // optional filter: pending, running, completed, failed
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                                // optional max number of actions (0 = all)
	NewestFirst   bool                   `protobuf:"varint,5,opt,name=newest_first,json=newestFirst,proto3" json:"newest_first,omitempty"` // if true sorts by created_at descending
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsRequest) Reset() {
	*x = ListActionsRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsRequest) ProtoMessage() {}

func (x *ListActionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsRequest.ProtoReflect.Descriptor instead.
func (*ListActionsRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ListActionsRequest) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *ListActionsRequest) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ListActionsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListActionsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListActionsRequest) GetNewestFirst() bool {
	if x != nil {
		return x.NewestFirst
	}
	return false
}

type AgentAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkloadId    string                 `protobuf:"bytes,2,opt,name=workload_id,json=workloadId,proto3" json:"workload_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     int64                  `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       int64                  `protobuf:"varint,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAction) Reset() {
	*x = AgentAction{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAction) ProtoMessage() {}

func (x *AgentAction) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAction.ProtoReflect.Descriptor instead.
func (*AgentAction) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *AgentAction) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AgentAction) GetWorkloadId() string {
	if x != nil {
		return x.WorkloadId
	}
	return ""
}

func (x *AgentAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *AgentAction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AgentAction) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentAction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *AgentAction) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *AgentAction) GetEndedAt() int64 {
	if x != nil {
		return x.EndedAt
	}
	return 0
}

type ListActionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actions       []*AgentAction         `protobuf:"bytes,1,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActionsResponse) Reset() {
	*x = ListActionsResponse{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActionsResponse) ProtoMessage() {}

func (x *ListActionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActionsResponse.ProtoReflect.Descriptor instead.
func (*ListActionsResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ListActionsResponse) GetActions() []*AgentAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

type WorkloadSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Spec:
	//
	//	*WorkloadSpec_Container
	//	*WorkloadSpec_Compose
	//	*WorkloadSpec_Vm
	Spec          isWorkloadSpec_Spec `protobuf_oneof:"spec"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadSpec) Reset() {
	*x = WorkloadSpec{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadSpec) ProtoMessage() {}

func (x *WorkloadSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadSpec.ProtoReflect.Descriptor instead.
func (*WorkloadSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *WorkloadSpec) GetSpec() isWorkloadSpec_Spec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *WorkloadSpec) GetContainer() *ContainerSpec {
	if x != nil {
		if x, ok := x.Spec.(*WorkloadSpec_Container); ok {
			return x.Container
		}
	}
	return nil
}

func (x *WorkloadSpec) GetCompose() *ComposeSpec {
	if x != nil {
		if x, ok := x.Spec.(*WorkloadSpec_Compose); ok {
			return x.Compose
		}
	}
	return nil
}

func (x *WorkloadSpec) GetVm() *VMSpec {
	if x != nil {
		if x, ok := x.Spec.(*WorkloadSpec_Vm); ok {
			return x.Vm
		}
	}
	return nil
}

type isWorkloadSpec_Spec interface {
	isWorkloadSpec_Spec()
}

type WorkloadSpec_Container struct {
	Container *ContainerSpec `protobuf:"bytes,1,opt,name=container,proto3,oneof"`
}

type WorkloadSpec_Compose struct {
	Compose *ComposeSpec `protobuf:"bytes,2,opt,name=compose,proto3,oneof"`
}

type WorkloadSpec_Vm struct {
	Vm *VMSpec `protobuf:"bytes,3,opt,name=vm,proto3,oneof"`
}

func (*WorkloadSpec_Container) isWorkloadSpec_Spec() {}

func (*WorkloadSpec_Compose) isWorkloadSpec_Spec() {}

func (*WorkloadSpec_Vm) isWorkloadSpec_Spec() {}

type ContainerSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Volumes       []*VolumeMount         `protobuf:"bytes,5,rep,name=volumes,proto3" json:"volumes,omitempty"`
	Ports         []*PortMapping         `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Resources     *ResourceLimits        `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	RestartPolicy *RestartPolicy         `protobuf:"bytes,8,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSpec) Reset() {
	*x = ContainerSpec{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSpec) ProtoMessage() {}

func (x *ContainerSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSpec.ProtoReflect.Descriptor instead.
func (*ContainerSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ContainerSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerSpec) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ContainerSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ContainerSpec) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *ContainerSpec) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ContainerSpec) GetResources() *ResourceLimits {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *ContainerSpec) GetRestartPolicy() *RestartPolicy {
	if x != nil {
		return x.RestartPolicy
	}
	return nil
}

func (x *ContainerSpec) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ComposeSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	ComposeYaml   string                 `protobuf:"bytes,2,opt,name=compose_yaml,json=composeYaml,proto3" json:"compose_yaml,omitempty"` // base64 encoded docker-compose.yml
	Env           map[string]string      `protobuf:"bytes,3,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComposeSpec) Reset() {
	*x = ComposeSpec{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComposeSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeSpec) ProtoMessage() {}

func (x *ComposeSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeSpec.ProtoReflect.Descriptor instead.
func (*ComposeSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ComposeSpec) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ComposeSpec) GetComposeYaml() string {
	if x != nil {
		return x.ComposeYaml
	}
	return ""
}

func (x *ComposeSpec) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

type VMSpec struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vcpus           int32                  `protobuf:"varint,2,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	MemoryMb        int64                  `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	Disks           []*DiskConfig          `protobuf:"bytes,4,rep,name=disks,proto3" json:"disks,omitempty"`
	Networks        []*NetworkConfig       `protobuf:"bytes,5,rep,name=networks,proto3" json:"networks,omitempty"`
	CloudInit       string                 `protobuf:"bytes,6,opt,name=cloud_init,json=cloudInit,proto3" json:"cloud_init,omitempty"` // optional cloud-init user-data (YAML content)
	Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CloudInitConfig *CloudInitConfig       `protobuf:"bytes,8,opt,name=cloud_init_config,json=cloudInitConfig,proto3" json:"cloud_init_config,omitempty"` // advanced cloud-init settings
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VMSpec) Reset() {
	*x = VMSpec{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMSpec) ProtoMessage() {}

func (x *VMSpec) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMSpec.ProtoReflect.Descriptor instead.
func (*VMSpec) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *VMSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VMSpec) GetVcpus() int32 {
	if x != nil {
		return x.Vcpus
	}
	return 0
}

func (x *VMSpec) GetMemoryMb() int64 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *VMSpec) GetDisks() []*DiskConfig {
	if x != nil {
		return x.Disks
	}
	return nil
}

func (x *VMSpec) GetNetworks() []*NetworkConfig {
	if x != nil {
		return x.Networks
	}
	return nil
}

func (x *VMSpec) GetCloudInit() string {
	if x != nil {
		return x.CloudInit
	}
	return ""
}

func (x *VMSpec) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *VMSpec) GetCloudInitConfig() *CloudInitConfig {
	if x != nil {
		return x.CloudInitConfig
	}
	return nil
}

type CloudInitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserData      string                 `protobuf:"bytes,1,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`                // cloud-init user-data script
	MetaData      string                 `protobuf:"bytes,2,opt,name=meta_data,json=metaData,proto3" json:"meta_data,omitempty"`                // cloud-init meta-data (JSON)
	NetworkConfig string                 `protobuf:"bytes,3,opt,name=network_config,json=networkConfig,proto3" json:"network_config,omitempty"` // cloud-init network config (YAML)
	VendorData    string                 `protobuf:"bytes,4,opt,name=vendor_data,json=vendorData,proto3" json:"vendor_data,omitempty"`          // cloud-init vendor-data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloudInitConfig) Reset() {
	*x = CloudInitConfig{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudInitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudInitConfig) ProtoMessage() {}

func (x *CloudInitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudInitConfig.ProtoReflect.Descriptor instead.
func (*CloudInitConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CloudInitConfig) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *CloudInitConfig) GetMetaData() string {
	if x != nil {
		return x.MetaData
	}
	return ""
}

func (x *CloudInitConfig) GetNetworkConfig() string {
	if x != nil {
		return x.NetworkConfig
	}
	return ""
}

func (x *CloudInitConfig) GetVendorData() string {
	if x != nil {
		return x.VendorData
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	ContainerPath string                 `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *VolumeMount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *VolumeMount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      int32                  `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort int32                  `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // tcp or udp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *PortMapping) GetHostPort() int32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetContainerPort() int32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type ResourceLimits struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CpuShares       int64                  `protobuf:"varint,1,opt,name=cpu_shares,json=cpuShares,proto3" json:"cpu_shares,omitempty"`
	MemoryBytes     int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	MemorySwapBytes int64                  `protobuf:"varint,3,opt,name=memory_swap_bytes,json=memorySwapBytes,proto3" json:"memory_swap_bytes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceLimits.ProtoReflect.Descriptor instead.
func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *ResourceLimits) GetCpuShares() int64 {
	if x != nil {
		return x.CpuShares
	}
	return 0
}

func (x *ResourceLimits) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *ResourceLimits) GetMemorySwapBytes() int64 {
	if x != nil {
		return x.MemorySwapBytes
	}
	return 0
}

type RestartPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        string                 `protobuf:"bytes,1,opt,name=policy,proto3" json:"policy,omitempty"` // no, always, on-failure, unless-stopped
	MaxRetryCount int32                  `protobuf:"varint,2,opt,name=max_retry_count,json=maxRetryCount,proto3" json:"max_retry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestartPolicy) Reset() {
	*x = RestartPolicy{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestartPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestartPolicy) ProtoMessage() {}

func (x *RestartPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestartPolicy.ProtoReflect.Descriptor instead.
func (*RestartPolicy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *RestartPolicy) GetPolicy() string {
	if x != nil {
		return x.Policy
	}
	return ""
}

func (x *RestartPolicy) GetMaxRetryCount() int32 {
	if x != nil {
		return x.MaxRetryCount
	}
	return 0
}

type DiskConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`     // path to disk image or ISO
	Device        string                 `protobuf:"bytes,2,opt,name=device,proto3" json:"device,omitempty"` // vda, vdb, etc.
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // qcow2, raw, iso
	SizeGb        int64                  `protobuf:"varint,4,opt,name=size_gb,json=sizeGb,proto3" json:"size_gb,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`  // disk or cdrom (for ISO)
	Boot          bool                   `protobuf:"varint,6,opt,name=boot,proto3" json:"boot,omitempty"` // true if this is the boot disk/ISO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiskConfig) Reset() {
	*x = DiskConfig{}
	mi := &file_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiskConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiskConfig) ProtoMessage() {}

func (x *DiskConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiskConfig.ProtoReflect.Descriptor instead.
func (*DiskConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{22}
}

func (x *DiskConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DiskConfig) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *DiskConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *DiskConfig) GetSizeGb() int64 {
	if x != nil {
		return x.SizeGb
	}
	return 0
}

func (x *DiskConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiskConfig) GetBoot() bool {
	if x != nil {
		return x.Boot
	}
	return false
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"` // network name or bridge
	MacAddress    string                 `protobuf:"bytes,2,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"` // optional static IP
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{23}
}

func (x *NetworkConfig) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *NetworkConfig) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

func (x *NetworkConfig) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type WorkloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          WorkloadType           `protobuf:"varint,2,opt,name=type,proto3,enum=persys.agent.v1.WorkloadType" json:"type,omitempty"`
	RevisionId    string                 `protobuf:"bytes,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	DesiredState  DesiredState           `protobuf:"varint,4,opt,name=desired_state,json=desiredState,proto3,enum=persys.agent.v1.DesiredState" json:"desired_state,omitempty"`
	ActualState   ActualState            `protobuf:"varint,5,opt,name=actual_state,json=actualState,proto3,enum=persys.agent.v1.ActualState" json:"actual_state,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadStatus) Reset() {
	*x = WorkloadStatus{}
	mi := &file_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadStatus) ProtoMessage() {}

func (x *WorkloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadStatus.ProtoReflect.Descriptor instead.
func (*WorkloadStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{24}
}

func (x *WorkloadStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkloadStatus) GetType() WorkloadType {
	if x != nil {
		return x.Type
	}
	return WorkloadType_WORKLOAD_TYPE_UNSPECIFIED
}

func (x *WorkloadStatus) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *WorkloadStatus) GetDesiredState() DesiredState {
	if x != nil {
		return x.DesiredState
	}
	return DesiredState_DESIRED_STATE_UNSPECIFIED
}

func (x *WorkloadStatus) GetActualState() ActualState {
	if x != nil {
		return x.ActualState
	}
	return ActualState_ACTUAL_STATE_UNSPECIFIED
}

func (x *WorkloadStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkloadStatus) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *WorkloadStatus) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *WorkloadStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0fpersys.agent.v1\"\xf1\x01\n" +
	"\x14ApplyWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.persys.agent.v1.WorkloadTypeR\x04type\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\tR\n" +
	"revisionId\x12B\n" +
	"\rdesired_state\x18\x04 \x01(\x0e2\x1d.persys.agent.v1.DesiredStateR\fdesiredState\x121\n" +
	"\x04spec\x18\x05 \x01(\v2\x1d.persys.agent.v1.WorkloadSpecR\x04spec\"\x9e\x01\n" +
	"\x15ApplyWorkloadResponse\x12\x18\n" +
	"\aapplied\x18\x01 \x01(\bR\aapplied\x12\x18\n" +
	"\askipped\x18\x02 \x01(\bR\askipped\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x127\n" +
	"\x06status\x18\x04 \x01(\v2\x1f.persys.agent.v1.WorkloadStatusR\x06status\"'\n" +
	"\x15DeleteWorkloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x16DeleteWorkloadResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"*\n" +
	"\x18GetWorkloadStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x19GetWorkloadStatusResponse\x127\n" +
	"\x06status\x18\x01 \x01(\v2\x1f.persys.agent.v1.WorkloadStatusR\x06status\"I\n" +
	"\x14ListWorkloadsRequest\x121\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1d.persys.agent.v1.WorkloadTypeR\x04type\"V\n" +
	"\x15ListWorkloadsResponse\x12=\n" +
	"\tworkloads\x18\x01 \x03(\v2\x1f.persys.agent.v1.WorkloadStatusR\tworkloads\"\x14\n" +
	"\x12HealthCheckRequest\"\xee\x02\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12^\n" +
	"\x0eruntime_status\x18\x03 \x03(\v27.persys.agent.v1.HealthCheckResponse.RuntimeStatusEntryR\rruntimeStatus\x12-\n" +
	"\x12memory_utilization\x18\x04 \x01(\x01R\x11memoryUtilization\x12'\n" +
	"\x0fcpu_utilization\x18\x05 \x01(\x01R\x0ecpuUtilization\x12)\n" +
	"\x10disk_utilization\x18\x06 \x01(\x01R\x0fdiskUtilization\x1a@\n" +
	"\x12RuntimeStatusEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa7\x01\n" +
	"\x12ListActionsRequest\x12\x1f\n" +
	"\vworkload_id\x18\x01 \x01(\tR\n" +
	"workloadId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12!\n" +
	"\fnewest_first\x18\x05 \x01(\bR\vnewestFirst\"\xef\x01\n" +
	"\vAgentAction\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1f\n" +
	"\vworkload_id\x18\x02 \x01(\tR\n" +
	"workloadId\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"started_at\x18\a \x01(\x03R\tstartedAt\x12\x19\n" +
	"\bended_at\x18\b \x01(\x03R\aendedAt\"M\n" +
	"\x13ListActionsResponse\x126\n" +
	"\aactions\x18\x01 \x03(\v2\x1c.persys.agent.v1.AgentActionR\aactions\"\xbb\x01\n" +
	"\fWorkloadSpec\x12>\n" +
	"\tcontainer\x18\x01 \x01(\v2\x1e.persys.agent.v1.ContainerSpecH\x00R\tcontainer\x128\n" +
	"\acompose\x18\x02 \x01(\v2\x1c.persys.agent.v1.ComposeSpecH\x00R\acompose\x12)\n" +
	"\x02vm\x18\x03 \x01(\v2\x17.persys.agent.v1.VMSpecH\x00R\x02vmB\x06\n" +
	"\x04spec\"\xb7\x04\n" +
	"\rContainerSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x03 \x03(\tR\x04args\x129\n" +
	"\x03env\x18\x04 \x03(\v2'.persys.agent.v1.ContainerSpec.EnvEntryR\x03env\x126\n" +
	"\avolumes\x18\x05 \x03(\v2\x1c.persys.agent.v1.VolumeMountR\avolumes\x122\n" +
	"\x05ports\x18\x06 \x03(\v2\x1c.persys.agent.v1.PortMappingR\x05ports\x12=\n" +
	"\tresources\x18\a \x01(\v2\x1f.persys.agent.v1.ResourceLimitsR\tresources\x12E\n" +
	"\x0erestart_policy\x18\b \x01(\v2\x1e.persys.agent.v1.RestartPolicyR\rrestartPolicy\x12B\n" +
	"\x06labels\x18\t \x03(\v2*.persys.agent.v1.ContainerSpec.LabelsEntryR\x06labels\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc4\x01\n" +
	"\vComposeSpec\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12!\n" +
	"\fcompose_yaml\x18\x02 \x01(\tR\vcomposeYaml\x127\n" +
	"\x03env\x18\x03 \x03(\v2%.persys.agent.v1.ComposeSpec.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x03\n" +
	"\x06VMSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05vcpus\x18\x02 \x01(\x05R\x05vcpus\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\x03R\bmemoryMb\x121\n" +
	"\x05disks\x18\x04 \x03(\v2\x1b.persys.agent.v1.DiskConfigR\x05disks\x12:\n" +
	"\bnetworks\x18\x05 \x03(\v2\x1e.persys.agent.v1.NetworkConfigR\bnetworks\x12\x1d\n" +
	"\n" +
	"cloud_init\x18\x06 \x01(\tR\tcloudInit\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.persys.agent.v1.VMSpec.MetadataEntryR\bmetadata\x12L\n" +
	"\x11cloud_init_config\x18\b \x01(\v2 .persys.agent.v1.CloudInitConfigR\x0fcloudInitConfig\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x0fCloudInitConfig\x12\x1b\n" +
	"\tuser_data\x18\x01 \x01(\tR\buserData\x12\x1b\n" +
	"\tmeta_data\x18\x02 \x01(\tR\bmetaData\x12%\n" +
	"\x0enetwork_config\x18\x03 \x01(\tR\rnetworkConfig\x12\x1f\n" +
	"\vvendor_data\x18\x04 \x01(\tR\n" +
	"vendorData\"n\n" +
	"\vVolumeMount\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\"m\n" +
	"\vPortMapping\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\x05R\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\x05R\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"~\n" +
	"\x0eResourceLimits\x12\x1d\n" +
	"\n" +
	"cpu_shares\x18\x01 \x01(\x03R\tcpuShares\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12*\n" +
	"\x11memory_swap_bytes\x18\x03 \x01(\x03R\x0fmemorySwapBytes\"O\n" +
	"\rRestartPolicy\x12\x16\n" +
	"\x06policy\x18\x01 \x01(\tR\x06policy\x12&\n" +
	"\x0fmax_retry_count\x18\x02 \x01(\x05R\rmaxRetryCount\"\x91\x01\n" +
	"\n" +
	"DiskConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06device\x18\x02 \x01(\tR\x06device\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x17\n" +
	"\asize_gb\x18\x04 \x01(\x03R\x06sizeGb\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04boot\x18\x06 \x01(\bR\x04boot\"i\n" +
	"\rNetworkConfig\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x1f\n" +
	"\vmac_address\x18\x02 \x01(\tR\n" +
	"macAddress\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x03 \x01(\tR\tipAddress\"\xd9\x03\n" +
	"\x0eWorkloadStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1d.persys.agent.v1.WorkloadTypeR\x04type\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\tR\n" +
	"revisionId\x12B\n" +
	"\rdesired_state\x18\x04 \x01(\x0e2\x1d.persys.agent.v1.DesiredStateR\fdesiredState\x12?\n" +
	"\factual_state\x18\x05 \x01(\x0e2\x1c.persys.agent.v1.ActualStateR\vactualState\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12I\n" +
	"\bmetadata\x18\t \x03(\v2-.persys.agent.v1.WorkloadStatus.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*{\n" +
	"\fWorkloadType\x12\x1d\n" +
	"\x19WORKLOAD_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WORKLOAD_TYPE_CONTAINER\x10\x01\x12\x19\n" +
	"\x15WORKLOAD_TYPE_COMPOSE\x10\x02\x12\x14\n" +
	"\x10WORKLOAD_TYPE_VM\x10\x03*c\n" +
	"\fDesiredState\x12\x1d\n" +
	"\x19DESIRED_STATE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DESIRED_STATE_RUNNING\x10\x01\x12\x19\n" +
	"\x15DESIRED_STATE_STOPPED\x10\x02*\xac\x01\n" +
	"\vActualState\x12\x1c\n" +
	"\x18ACTUAL_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ACTUAL_STATE_PENDING\x10\x01\x12\x18\n" +
	"\x14ACTUAL_STATE_RUNNING\x10\x02\x12\x18\n" +
	"\x14ACTUAL_STATE_STOPPED\x10\x03\x12\x17\n" +
	"\x13ACTUAL_STATE_FAILED\x10\x04\x12\x18\n" +
	"\x14ACTUAL_STATE_UNKNOWN\x10\x052\xd1\x04\n" +
	"\fAgentService\x12^\n" +
	"\rApplyWorkload\x12%.persys.agent.v1.ApplyWorkloadRequest\x1a&.persys.agent.v1.ApplyWorkloadResponse\x12a\n" +
	"\x0eDeleteWorkload\x12&.persys.agent.v1.DeleteWorkloadRequest\x1a'.persys.agent.v1.DeleteWorkloadResponse\x12j\n" +
	"\x11GetWorkloadStatus\x12).persys.agent.v1.GetWorkloadStatusRequest\x1a*.persys.agent.v1.GetWorkloadStatusResponse\x12^\n" +
	"\rListWorkloads\x12%.persys.agent.v1.ListWorkloadsRequest\x1a&.persys.agent.v1.ListWorkloadsResponse\x12X\n" +
	"\vHealthCheck\x12#.persys.agent.v1.HealthCheckRequest\x1a$.persys.agent.v1.HealthCheckResponse\x12X\n" +
	"\vListActions\x12#.persys.agent.v1.ListActionsRequest\x1a$.persys.agent.v1.ListActionsResponseBNZLgithub.com/persys-dev/persys-cloud/persys-scheduler/internal/agentpb;agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_agent_proto_goTypes = []any{
	(WorkloadType)(0),                 // 0: persys.agent.v1.WorkloadType
	(DesiredState)(0),                 // 1: persys.agent.v1.DesiredState
	(ActualState)(0),                  // 2: persys.agent.v1.ActualState
	(*ApplyWorkloadRequest)(nil),      // 3: persys.agent.v1.ApplyWorkloadRequest
	(*ApplyWorkloadResponse)(nil),     // 4: persys.agent.v1.ApplyWorkloadResponse
	(*DeleteWorkloadRequest)(nil),     // 5: persys.agent.v1.DeleteWorkloadRequest
	(*DeleteWorkloadResponse)(nil),    // 6: persys.agent.v1.DeleteWorkloadResponse
	(*GetWorkloadStatusRequest)(nil),  // 7: persys.agent.v1.GetWorkloadStatusRequest
	(*GetWorkloadStatusResponse)(nil), // 8: persys.agent.v1.GetWorkloadStatusResponse
	(*ListWorkloadsRequest)(nil),      // 9: persys.agent.v1.ListWorkloadsRequest
	(*ListWorkloadsResponse)(nil),     // 10: persys.agent.v1.ListWorkloadsResponse
	(*HealthCheckRequest)(nil),        // 11: persys.agent.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),       // 12: persys.agent.v1.HealthCheckResponse
	(*ListActionsRequest)(nil),        // 13: persys.agent.v1.ListActionsRequest
	(*AgentAction)(nil),               // 14: persys.agent.v1.AgentAction
	(*ListActionsResponse)(nil),       // 15: persys.agent.v1.ListActionsResponse
	(*WorkloadSpec)(nil),              // 16: persys.agent.v1.WorkloadSpec
	(*ContainerSpec)(nil),             // 17: persys.agent.v1.ContainerSpec
	(*ComposeSpec)(nil),               // 18: persys.agent.v1.ComposeSpec
	(*VMSpec)(nil),                    // 19: persys.agent.v1.VMSpec
	(*CloudInitConfig)(nil),           // 20: persys.agent.v1.CloudInitConfig
	(*VolumeMount)(nil),               // 21: persys.agent.v1.VolumeMount
	(*PortMapping)(nil),               // 22: persys.agent.v1.PortMapping
	(*ResourceLimits)(nil),            // 23: persys.agent.v1.ResourceLimits
	(*RestartPolicy)(nil),             // 24: persys.agent.v1.RestartPolicy
	(*DiskConfig)(nil),                // 25: persys.agent.v1.DiskConfig
	(*NetworkConfig)(nil),             // 26: persys.agent.v1.NetworkConfig
	(*WorkloadStatus)(nil),            // 27: persys.agent.v1.WorkloadStatus
	nil,                               // 28: persys.agent.v1.HealthCheckResponse.RuntimeStatusEntry
	nil,                               // 29: persys.agent.v1.ContainerSpec.EnvEntry
	nil,                               // 30: persys.agent.v1.ContainerSpec.LabelsEntry
	nil,                               // 31: persys.agent.v1.ComposeSpec.EnvEntry
	nil,                               // 32: persys.agent.v1.VMSpec.MetadataEntry
	nil,                               // 33: persys.agent.v1.WorkloadStatus.MetadataEntry
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: persys.agent.v1.ApplyWorkloadRequest.type:type_name -> persys.agent.v1.WorkloadType
	1,  // 1: persys.agent.v1.ApplyWorkloadRequest.desired_state:type_name -> persys.agent.v1.DesiredState
	16, // 2: persys.agent.v1.ApplyWorkloadRequest.spec:type_name -> persys.agent.v1.WorkloadSpec
	27, // 3: persys.agent.v1.ApplyWorkloadResponse.status:type_name -> persys.agent.v1.WorkloadStatus
	27, // 4: persys.agent.v1.GetWorkloadStatusResponse.status:type_name -> persys.agent.v1.WorkloadStatus
	0,  // 5: persys.agent.v1.ListWorkloadsRequest.type:type_name -> persys.agent.v1.WorkloadType
	27, // 6: persys.agent.v1.ListWorkloadsResponse.workloads:type_name -> persys.agent.v1.WorkloadStatus
	28, // 7: persys.agent.v1.HealthCheckResponse.runtime_status:type_name -> persys.agent.v1.HealthCheckResponse.RuntimeStatusEntry
	14, // 8: persys.agent.v1.ListActionsResponse.actions:type_name -> persys.agent.v1.AgentAction
	17, // 9: persys.agent.v1.WorkloadSpec.container:type_name -> persys.agent.v1.ContainerSpec
	18, // 10: persys.agent.v1.WorkloadSpec.compose:type_name -> persys.agent.v1.ComposeSpec
	19, // 11: persys.agent.v1.WorkloadSpec.vm:type_name -> persys.agent.v1.VMSpec
	29, // 12: persys.agent.v1.ContainerSpec.env:type_name -> persys.agent.v1.ContainerSpec.EnvEntry
	21, // 13: persys.agent.v1.ContainerSpec.volumes:type_name -> persys.agent.v1.VolumeMount
	22, // 14: persys.agent.v1.ContainerSpec.ports:type_name -> persys.agent.v1.PortMapping
	23, // 15: persys.agent.v1.ContainerSpec.resources:type_name -> persys.agent.v1.ResourceLimits
	24, // 16: persys.agent.v1.ContainerSpec.restart_policy:type_name -> persys.agent.v1.RestartPolicy
	30, // 17: persys.agent.v1.ContainerSpec.labels:type_name -> persys.agent.v1.ContainerSpec.LabelsEntry
	31, // 18: persys.agent.v1.ComposeSpec.env:type_name -> persys.agent.v1.ComposeSpec.EnvEntry
	25, // 19: persys.agent.v1.VMSpec.disks:type_name -> persys.agent.v1.DiskConfig
	26, // 20: persys.agent.v1.VMSpec.networks:type_name -> persys.agent.v1.NetworkConfig
	32, // 21: persys.agent.v1.VMSpec.metadata:type_name -> persys.agent.v1.VMSpec.MetadataEntry
	20, // 22: persys.agent.v1.VMSpec.cloud_init_config:type_name -> persys.agent.v1.CloudInitConfig
	0,  // 23: persys.agent.v1.WorkloadStatus.type:type_name -> persys.agent.v1.WorkloadType
	1,  // 24: persys.agent.v1.WorkloadStatus.desired_state:type_name -> persys.agent.v1.DesiredState
	2,  // 25: persys.agent.v1.WorkloadStatus.actual_state:type_name -> persys.agent.v1.ActualState
	33, // 26: persys.agent.v1.WorkloadStatus.metadata:type_name -> persys.agent.v1.WorkloadStatus.MetadataEntry
	3,  // 27: persys.agent.v1.AgentService.ApplyWorkload:input_type -> persys.agent.v1.ApplyWorkloadRequest
	5,  // 28: persys.agent.v1.AgentService.DeleteWorkload:input_type -> persys.agent.v1.DeleteWorkloadRequest
	7,  // 29: persys.agent.v1.AgentService.GetWorkloadStatus:input_type -> persys.agent.v1.GetWorkloadStatusRequest
	9,  // 30: persys.agent.v1.AgentService.ListWorkloads:input_type -> persys.agent.v1.ListWorkloadsRequest
	11, // 31: persys.agent.v1.AgentService.HealthCheck:input_type -> persys.agent.v1.HealthCheckRequest
	13, // 32: persys.agent.v1.AgentService.ListActions:input_type -> persys.agent.v1.ListActionsRequest
	4,  // 33: persys.agent.v1.AgentService.ApplyWorkload:output_type -> persys.agent.v1.ApplyWorkloadResponse
	6,  // 34: persys.agent.v1.AgentService.DeleteWorkload:output_type -> persys.agent.v1.DeleteWorkloadResponse
	8,  // 35: persys.agent.v1.AgentService.GetWorkloadStatus:output_type -> persys.agent.v1.GetWorkloadStatusResponse
	10, // 36: persys.agent.v1.AgentService.ListWorkloads:output_type -> persys.agent.v1.ListWorkloadsResponse
	12, // 37: persys.agent.v1.AgentService.HealthCheck:output_type -> persys.agent.v1.HealthCheckResponse
	15, // 38: persys.agent.v1.AgentService.ListActions:output_type -> persys.agent.v1.ListActionsResponse
	33, // [33:39] is the sub-list for method output_type
	27, // [27:33] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*WorkloadSpec_Container)(nil),
		(*WorkloadSpec_Compose)(nil),
		(*WorkloadSpec_Vm)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
