// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/proto/forgery.proto

package forgeryv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForwardWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	ClusterId     string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Sender        string                 `protobuf:"bytes,5,opt,name=sender,proto3" json:"sender,omitempty"`
	Ref           string                 `protobuf:"bytes,6,opt,name=ref,proto3" json:"ref,omitempty"`
	Before        string                 `protobuf:"bytes,7,opt,name=before,proto3" json:"before,omitempty"`
	After         string                 `protobuf:"bytes,8,opt,name=after,proto3" json:"after,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,9,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	Verified      bool                   `protobuf:"varint,10,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWebhookRequest) Reset() {
	*x = ForwardWebhookRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWebhookRequest) ProtoMessage() {}

func (x *ForwardWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWebhookRequest.ProtoReflect.Descriptor instead.
func (*ForwardWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{0}
}

func (x *ForwardWebhookRequest) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *ForwardWebhookRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *ForwardWebhookRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ForwardWebhookRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ForwardWebhookRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *ForwardWebhookRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *ForwardWebhookRequest) GetBefore() string {
	if x != nil {
		return x.Before
	}
	return ""
}

func (x *ForwardWebhookRequest) GetAfter() string {
	if x != nil {
		return x.After
	}
	return ""
}

func (x *ForwardWebhookRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *ForwardWebhookRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type ForwardWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardWebhookResponse) Reset() {
	*x = ForwardWebhookResponse{}
	mi := &file_api_proto_forgery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardWebhookResponse) ProtoMessage() {}

func (x *ForwardWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardWebhookResponse.ProtoReflect.Descriptor instead.
func (*ForwardWebhookResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{1}
}

func (x *ForwardWebhookResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ForwardWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpsertProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	ClusterId     string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	BuildType     string                 `protobuf:"bytes,5,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	BuildMode     string                 `protobuf:"bytes,6,opt,name=build_mode,json=buildMode,proto3" json:"build_mode,omitempty"`
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	NexusRepo     string                 `protobuf:"bytes,8,opt,name=nexus_repo,json=nexusRepo,proto3" json:"nexus_repo,omitempty"`
	PipelineYaml  string                 `protobuf:"bytes,9,opt,name=pipeline_yaml,json=pipelineYaml,proto3" json:"pipeline_yaml,omitempty"`
	AutoDeploy    bool                   `protobuf:"varint,10,opt,name=auto_deploy,json=autoDeploy,proto3" json:"auto_deploy,omitempty"`
	ImageName     string                 `protobuf:"bytes,11,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertProjectRequest) Reset() {
	*x = UpsertProjectRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertProjectRequest) ProtoMessage() {}

func (x *UpsertProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertProjectRequest.ProtoReflect.Descriptor instead.
func (*UpsertProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{2}
}

func (x *UpsertProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertProjectRequest) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *UpsertProjectRequest) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *UpsertProjectRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *UpsertProjectRequest) GetBuildType() string {
	if x != nil {
		return x.BuildType
	}
	return ""
}

func (x *UpsertProjectRequest) GetBuildMode() string {
	if x != nil {
		return x.BuildMode
	}
	return ""
}

func (x *UpsertProjectRequest) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *UpsertProjectRequest) GetNexusRepo() string {
	if x != nil {
		return x.NexusRepo
	}
	return ""
}

func (x *UpsertProjectRequest) GetPipelineYaml() string {
	if x != nil {
		return x.PipelineYaml
	}
	return ""
}

func (x *UpsertProjectRequest) GetAutoDeploy() bool {
	if x != nil {
		return x.AutoDeploy
	}
	return false
}

func (x *UpsertProjectRequest) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type GetProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProjectRequest) Reset() {
	*x = GetProjectRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProjectRequest) ProtoMessage() {}

func (x *GetProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProjectRequest.ProtoReflect.Descriptor instead.
func (*GetProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{3}
}

func (x *GetProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListProjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsRequest) Reset() {
	*x = ListProjectsRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsRequest) ProtoMessage() {}

func (x *ListProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsRequest.ProtoReflect.Descriptor instead.
func (*ListProjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{4}
}

type DeleteProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProjectRequest) Reset() {
	*x = DeleteProjectRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProjectRequest) ProtoMessage() {}

func (x *DeleteProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteProjectRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl       string                 `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3" json:"repo_url,omitempty"`
	DefaultBranch string                 `protobuf:"bytes,3,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	ClusterId     string                 `protobuf:"bytes,4,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	BuildType     string                 `protobuf:"bytes,5,opt,name=build_type,json=buildType,proto3" json:"build_type,omitempty"`
	BuildMode     string                 `protobuf:"bytes,6,opt,name=build_mode,json=buildMode,proto3" json:"build_mode,omitempty"`
	Strategy      string                 `protobuf:"bytes,7,opt,name=strategy,proto3" json:"strategy,omitempty"`
	NexusRepo     string                 `protobuf:"bytes,8,opt,name=nexus_repo,json=nexusRepo,proto3" json:"nexus_repo,omitempty"`
	PipelineYaml  string                 `protobuf:"bytes,9,opt,name=pipeline_yaml,json=pipelineYaml,proto3" json:"pipeline_yaml,omitempty"`
	AutoDeploy    bool                   `protobuf:"varint,10,opt,name=auto_deploy,json=autoDeploy,proto3" json:"auto_deploy,omitempty"`
	ImageName     string                 `protobuf:"bytes,11,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_proto_forgery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{6}
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetRepoUrl() string {
	if x != nil {
		return x.RepoUrl
	}
	return ""
}

func (x *Project) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Project) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Project) GetBuildType() string {
	if x != nil {
		return x.BuildType
	}
	return ""
}

func (x *Project) GetBuildMode() string {
	if x != nil {
		return x.BuildMode
	}
	return ""
}

func (x *Project) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *Project) GetNexusRepo() string {
	if x != nil {
		return x.NexusRepo
	}
	return ""
}

func (x *Project) GetPipelineYaml() string {
	if x != nil {
		return x.PipelineYaml
	}
	return ""
}

func (x *Project) GetAutoDeploy() bool {
	if x != nil {
		return x.AutoDeploy
	}
	return false
}

func (x *Project) GetImageName() string {
	if x != nil {
		return x.ImageName
	}
	return ""
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Project       *Project               `protobuf:"bytes,3,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_api_proto_forgery_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ProjectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ListProjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Projects      []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectsResponse) Reset() {
	*x = ListProjectsResponse{}
	mi := &file_api_proto_forgery_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectsResponse) ProtoMessage() {}

func (x *ListProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectsResponse.ProtoReflect.Descriptor instead.
func (*ListProjectsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{8}
}

func (x *ListProjectsResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

type StoreGitHubCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserLogin     string                 `protobuf:"bytes,2,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Scopes        []string               `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGitHubCredentialRequest) Reset() {
	*x = StoreGitHubCredentialRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGitHubCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGitHubCredentialRequest) ProtoMessage() {}

func (x *StoreGitHubCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGitHubCredentialRequest.ProtoReflect.Descriptor instead.
func (*StoreGitHubCredentialRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{9}
}

func (x *StoreGitHubCredentialRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StoreGitHubCredentialRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *StoreGitHubCredentialRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *StoreGitHubCredentialRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ListUserRepositoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserLogin     string                 `protobuf:"bytes,2,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRepositoriesRequest) Reset() {
	*x = ListUserRepositoriesRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRepositoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRepositoriesRequest) ProtoMessage() {}

func (x *ListUserRepositoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRepositoriesRequest.ProtoReflect.Descriptor instead.
func (*ListUserRepositoriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{10}
}

func (x *ListUserRepositoriesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListUserRepositoriesRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

type Repository struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Owner         string                 `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CloneUrl      string                 `protobuf:"bytes,4,opt,name=clone_url,json=cloneUrl,proto3" json:"clone_url,omitempty"`
	Private       bool                   `protobuf:"varint,5,opt,name=private,proto3" json:"private,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_api_proto_forgery_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{11}
}

func (x *Repository) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Repository) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetCloneUrl() string {
	if x != nil {
		return x.CloneUrl
	}
	return ""
}

func (x *Repository) GetPrivate() bool {
	if x != nil {
		return x.Private
	}
	return false
}

type ListUserRepositoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Repositories  []*Repository          `protobuf:"bytes,3,rep,name=repositories,proto3" json:"repositories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRepositoriesResponse) Reset() {
	*x = ListUserRepositoriesResponse{}
	mi := &file_api_proto_forgery_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRepositoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRepositoriesResponse) ProtoMessage() {}

func (x *ListUserRepositoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRepositoriesResponse.ProtoReflect.Descriptor instead.
func (*ListUserRepositoriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{12}
}

func (x *ListUserRepositoriesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ListUserRepositoriesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ListUserRepositoriesResponse) GetRepositories() []*Repository {
	if x != nil {
		return x.Repositories
	}
	return nil
}

type RegisterWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserLogin     string                 `protobuf:"bytes,2,opt,name=user_login,json=userLogin,proto3" json:"user_login,omitempty"`
	Repository    string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	WebhookUrl    string                 `protobuf:"bytes,4,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	WebhookSecret string                 `protobuf:"bytes,5,opt,name=webhook_secret,json=webhookSecret,proto3" json:"webhook_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWebhookRequest) Reset() {
	*x = RegisterWebhookRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWebhookRequest) ProtoMessage() {}

func (x *RegisterWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWebhookRequest.ProtoReflect.Descriptor instead.
func (*RegisterWebhookRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterWebhookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterWebhookRequest) GetUserLogin() string {
	if x != nil {
		return x.UserLogin
	}
	return ""
}

func (x *RegisterWebhookRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *RegisterWebhookRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *RegisterWebhookRequest) GetWebhookSecret() string {
	if x != nil {
		return x.WebhookSecret
	}
	return ""
}

type TriggerBuildRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectName   string                 `protobuf:"bytes,1,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	Repository    string                 `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Ref           string                 `protobuf:"bytes,4,opt,name=ref,proto3" json:"ref,omitempty"`
	CommitSha     string                 `protobuf:"bytes,5,opt,name=commit_sha,json=commitSha,proto3" json:"commit_sha,omitempty"`
	Sender        string                 `protobuf:"bytes,6,opt,name=sender,proto3" json:"sender,omitempty"`
	Mode          string                 `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	EventType     string                 `protobuf:"bytes,8,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildRequest) Reset() {
	*x = TriggerBuildRequest{}
	mi := &file_api_proto_forgery_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildRequest) ProtoMessage() {}

func (x *TriggerBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerBuildRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerBuildRequest) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *TriggerBuildRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *TriggerBuildRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *TriggerBuildRequest) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

func (x *TriggerBuildRequest) GetCommitSha() string {
	if x != nil {
		return x.CommitSha
	}
	return ""
}

func (x *TriggerBuildRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *TriggerBuildRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *TriggerBuildRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type OperationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_api_proto_forgery_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_forgery_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_forgery_proto_rawDescGZIP(), []int{15}
}

func (x *OperationStatus) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *OperationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_proto_forgery_proto protoreflect.FileDescriptor

const file_api_proto_forgery_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/forgery.proto\x12\x11persys.forgery.v1\"\xad\x02\n" +
	"\x15ForwardWebhookRequest\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12\x16\n" +
	"\x06sender\x18\x05 \x01(\tR\x06sender\x12\x10\n" +
	"\x03ref\x18\x06 \x01(\tR\x03ref\x12\x16\n" +
	"\x06before\x18\a \x01(\tR\x06before\x12\x14\n" +
	"\x05after\x18\b \x01(\tR\x05after\x12!\n" +
	"\fpayload_json\x18\t \x01(\tR\vpayloadJson\x12\x1a\n" +
	"\bverified\x18\n" +
	" \x01(\bR\bverified\"N\n" +
	"\x16ForwardWebhookResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe9\x02\n" +
	"\x14UpsertProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12%\n" +
	"\x0edefault_branch\x18\x03 \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"build_type\x18\x05 \x01(\tR\tbuildType\x12\x1d\n" +
	"\n" +
	"build_mode\x18\x06 \x01(\tR\tbuildMode\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"nexus_repo\x18\b \x01(\tR\tnexusRepo\x12#\n" +
	"\rpipeline_yaml\x18\t \x01(\tR\fpipelineYaml\x12\x1f\n" +
	"\vauto_deploy\x18\n" +
	" \x01(\bR\n" +
	"autoDeploy\x12\x1d\n" +
	"\n" +
	"image_name\x18\v \x01(\tR\timageName\"'\n" +
	"\x11GetProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x15\n" +
	"\x13ListProjectsRequest\"*\n" +
	"\x14DeleteProjectRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xdc\x02\n" +
	"\aProject\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brepo_url\x18\x02 \x01(\tR\arepoUrl\x12%\n" +
	"\x0edefault_branch\x18\x03 \x01(\tR\rdefaultBranch\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x04 \x01(\tR\tclusterId\x12\x1d\n" +
	"\n" +
	"build_type\x18\x05 \x01(\tR\tbuildType\x12\x1d\n" +
	"\n" +
	"build_mode\x18\x06 \x01(\tR\tbuildMode\x12\x1a\n" +
	"\bstrategy\x18\a \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"nexus_repo\x18\b \x01(\tR\tnexusRepo\x12#\n" +
	"\rpipeline_yaml\x18\t \x01(\tR\fpipelineYaml\x12\x1f\n" +
	"\vauto_deploy\x18\n" +
	" \x01(\bR\n" +
	"autoDeploy\x12\x1d\n" +
	"\n" +
	"image_name\x18\v \x01(\tR\timageName\"q\n" +
	"\x0fProjectResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x124\n" +
	"\aproject\x18\x03 \x01(\v2\x1a.persys.forgery.v1.ProjectR\aproject\"N\n" +
	"\x14ListProjectsResponse\x126\n" +
	"\bprojects\x18\x01 \x03(\v2\x1a.persys.forgery.v1.ProjectR\bprojects\"\x91\x01\n" +
	"\x1cStoreGitHubCredentialRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_login\x18\x02 \x01(\tR\tuserLogin\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12\x16\n" +
	"\x06scopes\x18\x04 \x03(\tR\x06scopes\"U\n" +
	"\x1bListUserRepositoriesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_login\x18\x02 \x01(\tR\tuserLogin\"\x8a\x01\n" +
	"\n" +
	"Repository\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1b\n" +
	"\tclone_url\x18\x04 \x01(\tR\bcloneUrl\x12\x18\n" +
	"\aprivate\x18\x05 \x01(\bR\aprivate\"\x8b\x01\n" +
	"\x1cListUserRepositoriesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12A\n" +
	"\frepositories\x18\x03 \x03(\v2\x1d.persys.forgery.v1.RepositoryR\frepositories\"\xb8\x01\n" +
	"\x16RegisterWebhookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_login\x18\x02 \x01(\tR\tuserLogin\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12\x1f\n" +
	"\vwebhook_url\x18\x04 \x01(\tR\n" +
	"webhookUrl\x12%\n" +
	"\x0ewebhook_secret\x18\x05 \x01(\tR\rwebhookSecret\"\xf3\x01\n" +
	"\x13TriggerBuildRequest\x12!\n" +
	"\fproject_name\x18\x01 \x01(\tR\vprojectName\x12\x1e\n" +
	"\n" +
	"repository\x18\x02 \x01(\tR\n" +
	"repository\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x10\n" +
	"\x03ref\x18\x04 \x01(\tR\x03ref\x12\x1d\n" +
	"\n" +
	"commit_sha\x18\x05 \x01(\tR\tcommitSha\x12\x16\n" +
	"\x06sender\x18\x06 \x01(\tR\x06sender\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"event_type\x18\b \x01(\tR\teventType\";\n" +
	"\x0fOperationStatus\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x91\a\n" +
	"\x0eForgeryControl\x12e\n" +
	"\x0eForwardWebhook\x12(.persys.forgery.v1.ForwardWebhookRequest\x1a).persys.forgery.v1.ForwardWebhookResponse\x12\\\n" +
	"\rUpsertProject\x12'.persys.forgery.v1.UpsertProjectRequest\x1a\".persys.forgery.v1.ProjectResponse\x12V\n" +
	"\n" +
	"GetProject\x12$.persys.forgery.v1.GetProjectRequest\x1a\".persys.forgery.v1.ProjectResponse\x12_\n" +
	"\fListProjects\x12&.persys.forgery.v1.ListProjectsRequest\x1a'.persys.forgery.v1.ListProjectsResponse\x12\\\n" +
	"\rDeleteProject\x12'.persys.forgery.v1.DeleteProjectRequest\x1a\".persys.forgery.v1.OperationStatus\x12l\n" +
	"\x15StoreGitHubCredential\x12/.persys.forgery.v1.StoreGitHubCredentialRequest\x1a\".persys.forgery.v1.OperationStatus\x12w\n" +
	"\x14ListUserRepositories\x12..persys.forgery.v1.ListUserRepositoriesRequest\x1a/.persys.forgery.v1.ListUserRepositoriesResponse\x12`\n" +
	"\x0fRegisterWebhook\x12).persys.forgery.v1.RegisterWebhookRequest\x1a\".persys.forgery.v1.OperationStatus\x12Z\n" +
	"\fTriggerBuild\x12&.persys.forgery.v1.TriggerBuildRequest\x1a\".persys.forgery.v1.OperationStatusBPZNgithub.com/persys-dev/persys-cloud/persys-forgery/internal/forgeryv1;forgeryv1b\x06proto3"

var (
	file_api_proto_forgery_proto_rawDescOnce sync.Once
	file_api_proto_forgery_proto_rawDescData []byte
)

func file_api_proto_forgery_proto_rawDescGZIP() []byte {
	file_api_proto_forgery_proto_rawDescOnce.Do(func() {
		file_api_proto_forgery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_forgery_proto_rawDesc), len(file_api_proto_forgery_proto_rawDesc)))
	})
	return file_api_proto_forgery_proto_rawDescData
}

var file_api_proto_forgery_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_forgery_proto_goTypes = []any{
	(*ForwardWebhookRequest)(nil),        // 0: persys.forgery.v1.ForwardWebhookRequest
	(*ForwardWebhookResponse)(nil),       // 1: persys.forgery.v1.ForwardWebhookResponse
	(*UpsertProjectRequest)(nil),         // 2: persys.forgery.v1.UpsertProjectRequest
	(*GetProjectRequest)(nil),            // 3: persys.forgery.v1.GetProjectRequest
	(*ListProjectsRequest)(nil),          // 4: persys.forgery.v1.ListProjectsRequest
	(*DeleteProjectRequest)(nil),         // 5: persys.forgery.v1.DeleteProjectRequest
	(*Project)(nil),                      // 6: persys.forgery.v1.Project
	(*ProjectResponse)(nil),              // 7: persys.forgery.v1.ProjectResponse
	(*ListProjectsResponse)(nil),         // 8: persys.forgery.v1.ListProjectsResponse
	(*StoreGitHubCredentialRequest)(nil), // 9: persys.forgery.v1.StoreGitHubCredentialRequest
	(*ListUserRepositoriesRequest)(nil),  // 10: persys.forgery.v1.ListUserRepositoriesRequest
	(*Repository)(nil),                   // 11: persys.forgery.v1.Repository
	(*ListUserRepositoriesResponse)(nil), // 12: persys.forgery.v1.ListUserRepositoriesResponse
	(*RegisterWebhookRequest)(nil),       // 13: persys.forgery.v1.RegisterWebhookRequest
	(*TriggerBuildRequest)(nil),          // 14: persys.forgery.v1.TriggerBuildRequest
	(*OperationStatus)(nil),              // 15: persys.forgery.v1.OperationStatus
}
var file_api_proto_forgery_proto_depIdxs = []int32{
	6,  // 0: persys.forgery.v1.ProjectResponse.project:type_name -> persys.forgery.v1.Project
	6,  // 1: persys.forgery.v1.ListProjectsResponse.projects:type_name -> persys.forgery.v1.Project
	11, // 2: persys.forgery.v1.ListUserRepositoriesResponse.repositories:type_name -> persys.forgery.v1.Repository
	0,  // 3: persys.forgery.v1.ForgeryControl.ForwardWebhook:input_type -> persys.forgery.v1.ForwardWebhookRequest
	2,  // 4: persys.forgery.v1.ForgeryControl.UpsertProject:input_type -> persys.forgery.v1.UpsertProjectRequest
	3,  // 5: persys.forgery.v1.ForgeryControl.GetProject:input_type -> persys.forgery.v1.GetProjectRequest
	4,  // 6: persys.forgery.v1.ForgeryControl.ListProjects:input_type -> persys.forgery.v1.ListProjectsRequest
	5,  // 7: persys.forgery.v1.ForgeryControl.DeleteProject:input_type -> persys.forgery.v1.DeleteProjectRequest
	9,  // 8: persys.forgery.v1.ForgeryControl.StoreGitHubCredential:input_type -> persys.forgery.v1.StoreGitHubCredentialRequest
	10, // 9: persys.forgery.v1.ForgeryControl.ListUserRepositories:input_type -> persys.forgery.v1.ListUserRepositoriesRequest
	13, // 10: persys.forgery.v1.ForgeryControl.RegisterWebhook:input_type -> persys.forgery.v1.RegisterWebhookRequest
	14, // 11: persys.forgery.v1.ForgeryControl.TriggerBuild:input_type -> persys.forgery.v1.TriggerBuildRequest
	1,  // 12: persys.forgery.v1.ForgeryControl.ForwardWebhook:output_type -> persys.forgery.v1.ForwardWebhookResponse
	7,  // 13: persys.forgery.v1.ForgeryControl.UpsertProject:output_type -> persys.forgery.v1.ProjectResponse
	7,  // 14: persys.forgery.v1.ForgeryControl.GetProject:output_type -> persys.forgery.v1.ProjectResponse
	8,  // 15: persys.forgery.v1.ForgeryControl.ListProjects:output_type -> persys.forgery.v1.ListProjectsResponse
	15, // 16: persys.forgery.v1.ForgeryControl.DeleteProject:output_type -> persys.forgery.v1.OperationStatus
	15, // 17: persys.forgery.v1.ForgeryControl.StoreGitHubCredential:output_type -> persys.forgery.v1.OperationStatus
	12, // 18: persys.forgery.v1.ForgeryControl.ListUserRepositories:output_type -> persys.forgery.v1.ListUserRepositoriesResponse
	15, // 19: persys.forgery.v1.ForgeryControl.RegisterWebhook:output_type -> persys.forgery.v1.OperationStatus
	15, // 20: persys.forgery.v1.ForgeryControl.TriggerBuild:output_type -> persys.forgery.v1.OperationStatus
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_forgery_proto_init() }
func file_api_proto_forgery_proto_init() {
	if File_api_proto_forgery_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_forgery_proto_rawDesc), len(file_api_proto_forgery_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_forgery_proto_goTypes,
		DependencyIndexes: file_api_proto_forgery_proto_depIdxs,
		MessageInfos:      file_api_proto_forgery_proto_msgTypes,
	}.Build()
	File_api_proto_forgery_proto = out.File
	file_api_proto_forgery_proto_goTypes = nil
	file_api_proto_forgery_proto_depIdxs = nil
}
