services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    command: etcd --advertise-client-urls http://etcd:2379 --listen-client-urls http://0.0.0.0:2379
    ports:
      - "2379:2379"

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - etcd
    ports:
      - "8084:8084"
    environment:
      - ETCD_ENDPOINTS=etcd:2379
