name: Auto Assign
on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
    
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Assign to Team
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const teamName = 'core-007';
          const { data: teamMembers } = await github.teams.listMembersInOrg({ org: github.context.repo.owner, team_slug: teamName });
          const assignees = teamMembers.map(member => member.login);
          await github.issues.addAssignees({ owner: github.context.repo.owner, repo: github.context.repo.repo, issue_number: github.context.payload.pull_request.number, assignees: assignees });
    
