# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout with Submodules
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24
        cache: true
        
    - name: Build API Gateway
      working-directory: ./persys-gateway
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys Scheduler
      working-directory: ./persys-scheduler
      run: |
          go mod download
          cd cmd/scheduler && go build -o main

    - name: Build Persys Compute Agent
      working-directory: ./compute-agent
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys Federation
      working-directory: ./persys-federation
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys Forgery
      working-directory: ./persys-forgery
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys-intelligence
      working-directory: ./persys-intelligence
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys-automation
      working-directory: ./persys-automation
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persys-go-sdk
      working-directory: ./sdk
      run: |
          go mod download
          cd cmd && go build -o main
    
    - name: Build Persys-vault-manager
      working-directory: ./vault-manager
      run: |
          go mod download
          cd cmd && go build -o main

    - name: Build Persysctl
      working-directory: ./persysctl
      run: |
          go mod download
          cd cmd && go build -o main
