// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: automation.proto

package automationv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AutomationControl_CreatePolicy_FullMethodName  = "/persys.automation.v1.AutomationControl/CreatePolicy"
	AutomationControl_ListPolicies_FullMethodName  = "/persys.automation.v1.AutomationControl/ListPolicies"
	AutomationControl_EnablePolicy_FullMethodName  = "/persys.automation.v1.AutomationControl/EnablePolicy"
	AutomationControl_DisablePolicy_FullMethodName = "/persys.automation.v1.AutomationControl/DisablePolicy"
	AutomationControl_EvaluateNow_FullMethodName   = "/persys.automation.v1.AutomationControl/EvaluateNow"
	AutomationControl_ListAuditLog_FullMethodName  = "/persys.automation.v1.AutomationControl/ListAuditLog"
)

// AutomationControlClient is the client API for AutomationControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AutomationControlClient interface {
	CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	EnablePolicy(ctx context.Context, in *EnablePolicyRequest, opts ...grpc.CallOption) (*EnablePolicyResponse, error)
	DisablePolicy(ctx context.Context, in *DisablePolicyRequest, opts ...grpc.CallOption) (*DisablePolicyResponse, error)
	EvaluateNow(ctx context.Context, in *EvaluateNowRequest, opts ...grpc.CallOption) (*EvaluateNowResponse, error)
	ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error)
}

type automationControlClient struct {
	cc grpc.ClientConnInterface
}

func NewAutomationControlClient(cc grpc.ClientConnInterface) AutomationControlClient {
	return &automationControlClient{cc}
}

func (c *automationControlClient) CreatePolicy(ctx context.Context, in *CreatePolicyRequest, opts ...grpc.CallOption) (*CreatePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePolicyResponse)
	err := c.cc.Invoke(ctx, AutomationControl_CreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, AutomationControl_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlClient) EnablePolicy(ctx context.Context, in *EnablePolicyRequest, opts ...grpc.CallOption) (*EnablePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnablePolicyResponse)
	err := c.cc.Invoke(ctx, AutomationControl_EnablePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlClient) DisablePolicy(ctx context.Context, in *DisablePolicyRequest, opts ...grpc.CallOption) (*DisablePolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisablePolicyResponse)
	err := c.cc.Invoke(ctx, AutomationControl_DisablePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlClient) EvaluateNow(ctx context.Context, in *EvaluateNowRequest, opts ...grpc.CallOption) (*EvaluateNowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateNowResponse)
	err := c.cc.Invoke(ctx, AutomationControl_EvaluateNow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *automationControlClient) ListAuditLog(ctx context.Context, in *ListAuditLogRequest, opts ...grpc.CallOption) (*ListAuditLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAuditLogResponse)
	err := c.cc.Invoke(ctx, AutomationControl_ListAuditLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AutomationControlServer is the server API for AutomationControl service.
// All implementations must embed UnimplementedAutomationControlServer
// for forward compatibility.
type AutomationControlServer interface {
	CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	EnablePolicy(context.Context, *EnablePolicyRequest) (*EnablePolicyResponse, error)
	DisablePolicy(context.Context, *DisablePolicyRequest) (*DisablePolicyResponse, error)
	EvaluateNow(context.Context, *EvaluateNowRequest) (*EvaluateNowResponse, error)
	ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error)
	mustEmbedUnimplementedAutomationControlServer()
}

// UnimplementedAutomationControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAutomationControlServer struct{}

func (UnimplementedAutomationControlServer) CreatePolicy(context.Context, *CreatePolicyRequest) (*CreatePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePolicy not implemented")
}
func (UnimplementedAutomationControlServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedAutomationControlServer) EnablePolicy(context.Context, *EnablePolicyRequest) (*EnablePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnablePolicy not implemented")
}
func (UnimplementedAutomationControlServer) DisablePolicy(context.Context, *DisablePolicyRequest) (*DisablePolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisablePolicy not implemented")
}
func (UnimplementedAutomationControlServer) EvaluateNow(context.Context, *EvaluateNowRequest) (*EvaluateNowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateNow not implemented")
}
func (UnimplementedAutomationControlServer) ListAuditLog(context.Context, *ListAuditLogRequest) (*ListAuditLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAuditLog not implemented")
}
func (UnimplementedAutomationControlServer) mustEmbedUnimplementedAutomationControlServer() {}
func (UnimplementedAutomationControlServer) testEmbeddedByValue()                           {}

// UnsafeAutomationControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AutomationControlServer will
// result in compilation errors.
type UnsafeAutomationControlServer interface {
	mustEmbedUnimplementedAutomationControlServer()
}

func RegisterAutomationControlServer(s grpc.ServiceRegistrar, srv AutomationControlServer) {
	// If the following call panics, it indicates UnimplementedAutomationControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AutomationControl_ServiceDesc, srv)
}

func _AutomationControl_CreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).CreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_CreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).CreatePolicy(ctx, req.(*CreatePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControl_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControl_EnablePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).EnablePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_EnablePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).EnablePolicy(ctx, req.(*EnablePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControl_DisablePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisablePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).DisablePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_DisablePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).DisablePolicy(ctx, req.(*DisablePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControl_EvaluateNow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateNowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).EvaluateNow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_EvaluateNow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).EvaluateNow(ctx, req.(*EvaluateNowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AutomationControl_ListAuditLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAuditLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AutomationControlServer).ListAuditLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AutomationControl_ListAuditLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AutomationControlServer).ListAuditLog(ctx, req.(*ListAuditLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AutomationControl_ServiceDesc is the grpc.ServiceDesc for AutomationControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AutomationControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "persys.automation.v1.AutomationControl",
	HandlerType: (*AutomationControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePolicy",
			Handler:    _AutomationControl_CreatePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _AutomationControl_ListPolicies_Handler,
		},
		{
			MethodName: "EnablePolicy",
			Handler:    _AutomationControl_EnablePolicy_Handler,
		},
		{
			MethodName: "DisablePolicy",
			Handler:    _AutomationControl_DisablePolicy_Handler,
		},
		{
			MethodName: "EvaluateNow",
			Handler:    _AutomationControl_EvaluateNow_Handler,
		},
		{
			MethodName: "ListAuditLog",
			Handler:    _AutomationControl_ListAuditLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "automation.proto",
}
